insert into base.versions(id,version,updated_at,description)
values(next_id('base.versions'),'0.48.0',now(),'增加辅修专业报名支持');

alter table base.courses alter calgp set default true;
alter table base.courses alter has_makeup set default true;
alter table base.experiments alter category_id set not null;
alter table base.experiments alter discipline_id set not null;
alter table base.minor_majors add column department_id integer;
alter table base.minor_majors add constraint fk_3k2i9viyjisal7ne8ukvbigur foreign key (department_id) references base.departments (id);
comment on column base.minor_majors.department_id is '部门组织机构信息ID';
comment on table code.edu_categories is '教育类别';
comment on table code.teaching_natures is '课时分类';

create table std.minor_signup_options (id bigint not null, cur_count integer default 0 not null, major_id bigint not null, max_count integer, setting_id integer not null);
create table std.minor_signup_settings (id integer not null, begin_at timestamptz not null, end_at timestamptz, grade varchar(255) not null, name varchar(255) not null, project_id integer not null, updated_at timestamptz default current_timestamp not null);
create table std.minor_signup_std_majors (id bigint not null, idx integer default 0 not null, major_id bigint not null, std_id bigint not null);
create table std.minor_signup_stds (id bigint not null, address varchar(255), birthday date not null, category_id integer, code varchar(255) not null, department varchar(255) not null, from_org varchar(255), from_social boolean default false not null, gender_id integer not null, gpa float4, idcard varchar(255) not null, inside boolean default false not null, institution_id integer not null, major varchar(255) not null, mobile varchar(255) not null, name varchar(255) not null, photo_path varchar(255), setting_id integer not null, squad varchar(255), updated_at timestamptz default current_timestamp not null);

alter table std.minor_signup_options add constraint pk_bjytbcxuwc4h61ffiqgvo0ytq primary key (id);
alter table std.minor_signup_settings add constraint pk_lbdv0iilu1f78dkfta76ob83p primary key (id);
alter table std.minor_signup_std_majors add constraint pk_4mc1rl2t3d6ficldtdl901qou primary key (id);
alter table std.minor_signup_stds add constraint pk_531wskv253921k4m6949sn2ir primary key (id);
alter table std.minor_signup_options add constraint fk_42t72mbjc6mw0thib3v1wshrk foreign key (major_id) references base.minor_majors (id);
alter table std.minor_signup_options add constraint fk_ip4ipdmxiyo2iuboed7whyofe foreign key (setting_id) references std.minor_signup_settings (id);
alter table std.minor_signup_settings add constraint fk_44iq2pwbkab24k9e5mweoecxs foreign key (project_id) references base.projects (id);
alter table std.minor_signup_std_majors add constraint fk_rg6p98r4bpxlmusrdxjd6mqvr foreign key (std_id) references std.minor_signup_stds (id);
alter table std.minor_signup_std_majors add constraint fk_c9npq9pgbcrhy893tq5n54rxc foreign key (major_id) references base.minor_majors (id);
alter table std.minor_signup_stds add constraint fk_llys1ya5u6mbnflrrmoarbobj foreign key (gender_id) references code.genders (id);
alter table std.minor_signup_stds add constraint fk_9qgk9thlvafo1f6i0rv1idqt1 foreign key (setting_id) references std.minor_signup_settings (id);
alter table std.minor_signup_stds add constraint fk_ggee3uuam9r91bpfjcrh05d98 foreign key (institution_id) references code.institutions (id);
alter table std.minor_signup_stds add constraint fk_52nhs8fsp9uqvecbhgxn0emnl foreign key (category_id) references code.discipline_categories (id);
alter table std.minor_signup_stds add constraint uk_mcjo5arixiaveju23pqxqx6aa unique (setting_id,idcard);
create index idx_hjdfk644ni1xpod3illklvkaq on std.minor_signup_options (setting_id);
create index idx_aadu02hae1lacj76cy1lkwprt on std.minor_signup_std_majors (std_id);
create index idx_gnj9mmkdkggyt2s4q6t6iljyl on std.minor_signup_stds (setting_id);
comment on table std.minor_signup_options is '报名专业设置@minor';
comment on column std.minor_signup_options.id is '非业务主键:datetime';
comment on column std.minor_signup_options.cur_count is '当前人数';
comment on column std.minor_signup_options.major_id is '辅修专业ID';
comment on column std.minor_signup_options.max_count is '最大人数';
comment on column std.minor_signup_options.setting_id is '学生报名设置ID';
comment on table std.minor_signup_settings is '学生报名设置@minor';
comment on column std.minor_signup_settings.id is '非业务主键:auto_increment';
comment on column std.minor_signup_settings.begin_at is '生效时间';
comment on column std.minor_signup_settings.end_at is '失效时间';
comment on column std.minor_signup_settings.grade is '年级';
comment on column std.minor_signup_settings.name is '名称';
comment on column std.minor_signup_settings.project_id is '项目ID';
comment on column std.minor_signup_settings.updated_at is '更新时间';
comment on table std.minor_signup_std_majors is '学生报名志愿和专业@minor';
comment on column std.minor_signup_std_majors.id is '非业务主键:datetime';
comment on column std.minor_signup_std_majors.idx is '志愿号(1开始)';
comment on column std.minor_signup_std_majors.major_id is '辅修专业ID';
comment on column std.minor_signup_std_majors.std_id is '学生报名信息ID';
comment on table std.minor_signup_stds is '学生报名信息@minor';
comment on column std.minor_signup_stds.id is '非业务主键:datetime';
comment on column std.minor_signup_stds.address is '地址';
comment on column std.minor_signup_stds.birthday is '出生日期';
comment on column std.minor_signup_stds.category_id is '学科门类ID';
comment on column std.minor_signup_stds.code is '代码';
comment on column std.minor_signup_stds.department is '院系';
comment on column std.minor_signup_stds.from_org is '所在单位';
comment on column std.minor_signup_stds.from_social is '是否社会学院';
comment on column std.minor_signup_stds.gender_id is '性别ID';
comment on column std.minor_signup_stds.gpa is '绩点';
comment on column std.minor_signup_stds.idcard is '身份证号';
comment on column std.minor_signup_stds.inside is '是否校内学生';
comment on column std.minor_signup_stds.institution_id is '学校ID';
comment on column std.minor_signup_stds.major is '主修专业';
comment on column std.minor_signup_stds.mobile is '电话';
comment on column std.minor_signup_stds.name is '名称';
comment on column std.minor_signup_stds.photo_path is '照片路径';
comment on column std.minor_signup_stds.setting_id is '学生报名设置ID';
comment on column std.minor_signup_stds.squad is '班级';
comment on column std.minor_signup_stds.updated_at is '更新时间';

