insert into base.versions(id,version,updated_at,description)
values(next_id('base.versions'),'0.41.0',now(),'增加教案支持');

--syllabus
alter table edu.syllabus_experiments add column experiment_id bigint;
alter table edu.syllabus_experiments alter name type varchar(255);
alter table edu.syllabuses alter end_on set not null;

--clazz_plans
alter table edu.teaching_plans rename to clazz_plans;
alter table edu.teaching_plan_sections to clazz_section_hours;

create table base.experiments (id bigint not null, begin_on date not null, category_id integer not null, code varchar(255) not null, course_id bigint not null, credit_hours integer default 0 not null, discipline_id integer not null, en_name varchar(255), end_on date, experiment_type_id integer not null, group_std_count integer default 0 not null, name varchar(255) not null, online boolean default false not null, project_id integer not null);
create table base.experiments_levels (education_level_id integer not null, experiment_id bigint not null);
create table base.laboratories (id bigint not null, begin_on date not null, building_id integer, campus_id integer not null, code varchar(20) not null, end_on date, name varchar(100) not null, room_no varchar(20), school_id integer not null, short_name varchar(255), updated_at timestamptz default current_timestamp not null);
create table code.experiment_categories (id integer not null, begin_on date not null, code varchar(20) not null, en_name varchar(300), end_on date, name varchar(100) not null, remark varchar(200), updated_at timestamptz default current_timestamp not null);
create table code.level1_disciplines (id integer not null, begin_on date not null, category_id integer not null, code varchar(20) not null, en_name varchar(300), end_on date, name varchar(100) not null, remark varchar(200), updated_at timestamptz default current_timestamp not null);
create table edu.clazz_programs (id bigint not null, clazz_id bigint not null, semester_id integer not null, updated_at timestamptz default current_timestamp not null, writer_id bigint not null);
create table edu.lesson_design_sections (id bigint not null, design_id bigint not null, details varchar(3000) not null, duration integer default 0 not null, idx integer default 0 not null, summary varchar(1000) not null, title varchar(200) not null);
create table edu.lesson_design_texts (id bigint not null, contents varchar(4000) not null, design_id bigint not null, name varchar(100) not null);
create table edu.lesson_designs (id bigint not null, credit_hours integer default 0 not null, file_path varchar(255), homework varchar(255), idx integer default 0 not null, program_id bigint not null, remark varchar(255), subject varchar(255) not null);


alter table base.experiments add constraint pk_9bocam72pq84nbf7q7r1jn5py primary key (id);
alter table base.experiments_levels add constraint pk_kj340wjteh4rn3r4ot248bec3 primary key (experiment_id,education_level_id);
alter table base.laboratories add constraint pk_217f1ui65li444828qnn85h1d primary key (id);
alter table code.experiment_categories add constraint pk_kcu5rbl4kuot4icst1glh5167 primary key (id);
alter table code.level1_disciplines add constraint pk_6kymaieloxnmdimt05r4bie0q primary key (id);
alter table edu.clazz_programs add constraint pk_20l3sep385iuu3rtvbay24j3m primary key (id);
alter table edu.lesson_design_sections add constraint pk_8kppfknajixthr1k69jiv7rp3 primary key (id);
alter table edu.lesson_design_texts add constraint pk_bx15i5djo5j3acv624ecygp6i primary key (id);
alter table edu.lesson_designs add constraint pk_q7x9xap0fvw6fl1yivtswgfgq primary key (id);
alter table base.experiments add constraint fk_j4upj8ugk50h75xid7oxxc4dd foreign key (project_id) references base.projects (id);
alter table base.experiments add constraint fk_syicnxr0u0po3ou1cf9l1n1so foreign key (discipline_id) references code.level1_disciplines (id);
alter table base.experiments add constraint fk_bsj5luxworu1ale3fq4bv5m7h foreign key (experiment_type_id) references code.experiment_types (id);
alter table base.experiments add constraint fk_cnbo41vj9grh5xljkjie3jiw5 foreign key (course_id) references base.courses (id);
alter table base.experiments add constraint fk_qdjbtewk6kkhmrrlcxkrr6h6 foreign key (category_id) references code.experiment_categories (id);
alter table base.experiments_levels add constraint fk_nv7d7iye3jlfwue1884yp0k5d foreign key (experiment_id) references base.experiments (id);
alter table base.experiments_levels add constraint fk_bp5u3w9vs8ehg8hnt7f88voic foreign key (education_level_id) references code.education_levels (id);
alter table base.laboratories add constraint fk_kadqxrk7yv9gvuh7gui93wci5 foreign key (campus_id) references base.campuses (id);
alter table base.laboratories add constraint fk_9n6gopv0qgujb6fyah77a1n1w foreign key (building_id) references base.buildings (id);
alter table base.laboratories add constraint fk_j94hdmq0cx18wd3kvbvwvn4vn foreign key (school_id) references base.schools (id);
alter table code.level1_disciplines add constraint fk_pf209fc8t60gdq3omladrg0br foreign key (category_id) references code.discipline_categories (id);
alter table edu.clazz_programs add constraint fk_tph7qlshfbw43yu6olctyp9fy foreign key (semester_id) references base.semesters (id);
alter table edu.clazz_programs add constraint fk_4crby07kat6870f1fywdjqfnb foreign key (writer_id) references base.users (id);
alter table edu.clazz_programs add constraint fk_h9ailuws5qiohxfl6gqmnww7h foreign key (clazz_id) references edu.clazzes (id);
alter table edu.lesson_design_sections add constraint fk_sekm4iwyl9v2swbnvvfhfhmny foreign key (design_id) references edu.lesson_designs (id);
alter table edu.lesson_design_texts add constraint fk_rl5n4rr7r7arp6byxx46hekea foreign key (design_id) references edu.lesson_designs (id);
alter table edu.lesson_designs add constraint fk_28csuwjgk7l8p9cex45revrws foreign key (program_id) references edu.clazz_programs (id);
alter table edu.syllabus_experiments add constraint fk_8d9d58buigjgts7ix2fjdmaqe foreign key (experiment_id) references base.experiments (id);
alter table base.laboratories add constraint uk_2quxs44337ol9rk7t7g6x5pha unique (school_id,code);
alter table code.experiment_categories add constraint uk_hlkv8756ovpp91ql6d1hsil6d unique (code);
alter table code.level1_disciplines add constraint uk_oc1wjadmqun61ry6dba697cwm unique (code);
create index idx_3lcghho5tdhwx1u678giqq2xo on base.experiments_levels (experiment_id);
create index idx_48i0k0l7gf2fg5d5m381gpofl on edu.lesson_design_sections (design_id);
create index idx_8w3m21matxhg8f1tg60m1lbqi on edu.lesson_design_texts (design_id);
create index idx_gif3ffmlcf3l41h1a6bxtrjh2 on edu.lesson_designs (program_id);
comment on table base.experiments is '实验项目@edu';
comment on column base.experiments.id is '非业务主键:datetime';
comment on column base.experiments.begin_on is '生效日期';
comment on column base.experiments.category_id is '实验类别ID';
comment on column base.experiments.code is '代码';
comment on column base.experiments.course_id is '课程基本信息ID';
comment on column base.experiments.credit_hours is '学时';
comment on column base.experiments.discipline_id is '一级学科ID';
comment on column base.experiments.en_name is '英文名';
comment on column base.experiments.end_on is '失效日期';
comment on column base.experiments.experiment_type_id is '实验类型ID';
comment on column base.experiments.group_std_count is '每组人数';
comment on column base.experiments.name is '名称';
comment on column base.experiments.online is '是否在线实验';
comment on column base.experiments.project_id is '项目ID';
comment on table base.experiments_levels is '实验项目对应培养层次@edu';
comment on column base.experiments_levels.education_level_id is '培养层次ID';
comment on column base.experiments_levels.experiment_id is '实验项目ID';
comment on table base.laboratories is '实验室@resource';
comment on column base.laboratories.id is '非业务主键:datetime';
comment on column base.laboratories.begin_on is '生效日期';
comment on column base.laboratories.building_id is '楼房建筑物ID';
comment on column base.laboratories.campus_id is '校区信息ID';
comment on column base.laboratories.code is '代码';
comment on column base.laboratories.end_on is '失效日期';
comment on column base.laboratories.name is '名称';
comment on column base.laboratories.room_no is '房间号';
comment on column base.laboratories.school_id is '学校信息ID';
comment on column base.laboratories.short_name is '简称';
comment on column base.laboratories.updated_at is '更新时间';
comment on table code.experiment_categories is '实验类别@edu';
comment on column code.experiment_categories.id is '非业务主键:code';
comment on column code.experiment_categories.begin_on is '生效日期';
comment on column code.experiment_categories.code is '代码';
comment on column code.experiment_categories.en_name is '英文名称';
comment on column code.experiment_categories.end_on is '失效日期';
comment on column code.experiment_categories.name is '名称';
comment on column code.experiment_categories.remark is '备注';
comment on column code.experiment_categories.updated_at is '修改时间';
comment on table code.level1_disciplines is '一级学科@edu';
comment on column code.level1_disciplines.id is '非业务主键:code';
comment on column code.level1_disciplines.begin_on is '生效日期';
comment on column code.level1_disciplines.category_id is '学科门类ID';
comment on column code.level1_disciplines.code is '代码';
comment on column code.level1_disciplines.en_name is '英文名称';
comment on column code.level1_disciplines.end_on is '失效日期';
comment on column code.level1_disciplines.name is '名称';
comment on column code.level1_disciplines.remark is '备注';
comment on column code.level1_disciplines.updated_at is '修改时间';
comment on table edu.clazz_plans is '授课计划@course';
comment on column edu.clazz_plans.id is '非业务主键:datetime';
comment on column edu.clazz_plans.approver_id is '通用人员信息ID';
comment on column edu.clazz_plans.clazz_id is '教学任务ID';
comment on column edu.clazz_plans.exam_hours is '考核课时';
comment on column edu.clazz_plans.file_path is '附件关键字';
comment on column edu.clazz_plans.lesson_hours is '课堂课时';
comment on column edu.clazz_plans.office_id is '教研室ID';
comment on column edu.clazz_plans.opinions is '驳回意见';
comment on column edu.clazz_plans.publish_at is '发布时间';
comment on column edu.clazz_plans.reviewer_id is '通用人员信息ID';
comment on column edu.clazz_plans.semester_id is '学年学期ID';
comment on column edu.clazz_plans.status is '状态';
comment on column edu.clazz_plans.updated_at is '更新时间';
comment on column edu.clazz_plans.writer_id is '通用人员信息ID';
comment on table edu.clazz_programs is '教案@course';
comment on column edu.clazz_programs.id is '非业务主键:datetime';
comment on column edu.clazz_programs.clazz_id is '教学任务ID';
comment on column edu.clazz_programs.semester_id is '学年学期ID';
comment on column edu.clazz_programs.updated_at is '更新时间';
comment on column edu.clazz_programs.writer_id is '作者ID';
comment on table edu.clazz_section_hours is '环节课时@course';
comment on column edu.clazz_section_hours.id is '非业务主键:datetime';
comment on column edu.clazz_section_hours.credit_hours is '课时';
comment on column edu.clazz_section_hours.name is '名称';
comment on column edu.clazz_section_hours.plan_id is '授课计划ID';
comment on table edu.lesson_design_sections is '教案课程设计-课程设计环节@course';
comment on column edu.lesson_design_sections.id is '非业务主键:datetime';
comment on column edu.lesson_design_sections.design_id is '教案课程设计ID';
comment on column edu.lesson_design_sections.details is '教学过程设计';
comment on column edu.lesson_design_sections.duration is '时长';
comment on column edu.lesson_design_sections.idx is '序号';
comment on column edu.lesson_design_sections.summary is '教学内容提要';
comment on column edu.lesson_design_sections.title is '标题';
comment on table edu.lesson_design_texts is '教案课程设计文本@course';
comment on column edu.lesson_design_texts.id is '非业务主键:datetime';
comment on column edu.lesson_design_texts.contents is '内容';
comment on column edu.lesson_design_texts.design_id is '教案课程设计ID';
comment on column edu.lesson_design_texts.name is '名称';
comment on table edu.lesson_designs is '教案课程设计@course';
comment on column edu.lesson_designs.id is '非业务主键:datetime';
comment on column edu.lesson_designs.credit_hours is '学时';
comment on column edu.lesson_designs.file_path is '附件路径';
comment on column edu.lesson_designs.homework is '作业';
comment on column edu.lesson_designs.idx is '序号';
comment on column edu.lesson_designs.program_id is '教案ID';
comment on column edu.lesson_designs.remark is '备注';
comment on column edu.lesson_designs.subject is '主题';
comment on table edu.syllabus_hours is '教学大纲-分类课时@course';
comment on column edu.syllabus_hours.id is '非业务主键:datetime';
comment on column edu.syllabus_hours.credit_hours is '学时';
comment on column edu.syllabus_hours.nature_id is '授课性质ID';
comment on column edu.syllabus_hours.syllabus_id is '课程教学大纲ID';
comment on column edu.syllabus_experiments.experiment_id is '实验项目ID';
comment on column edu.syllabuses.weeks is '实践周';
comment on column edu.syllabuses.end_on is '结束日期';

