alter table base.buildings add constraint pk_isptetvkhnkbsd7qqyed4vjy6 primary key (id);
alter table base.buildings add constraint uk_57bnctn8fdawxdyp9lpaxbgjt unique (school_id,code);
alter table base.calendar_stages add constraint pk_bwq0g3d1exgmi6u4ss0me8y3m primary key (id);
alter table base.calendars add constraint pk_b2bvaskon8lysbk1srdwtml4f primary key (id);
alter table base.calendars add constraint uk_9k89gny3vqpqyk7mkhuxg16fi unique (school_id,code);
alter table base.campuses add constraint pk_7b3jpnegqwbvpg4marvqwpn46 primary key (id);
alter table base.campuses add constraint uk_iyq5494wgreojxq596lo7iijs unique (school_id,code);
alter table base.classrooms add constraint pk_d7h30ub9pduroys2e5318ti55 primary key (id);
alter table base.classrooms add constraint uk_t23e7c95vph4sm7nva099kab0 unique (school_id,code);
alter table base.classrooms_departs add constraint pk_n5duwpuh4oq58kk8i61odk7h7 primary key (classroom_id,department_id);
alter table base.classrooms_projects add constraint pk_cjgojafxa077u3fb2vicargx primary key (classroom_id,project_id);
alter table base.course_awards add constraint pk_cmuxxfg5u142t0vjm3gvex2w3 primary key (id);
alter table base.course_clusters add constraint pk_6gjj4kp1e06ob51efr5det0ot primary key (id);
alter table base.course_directors add constraint pk_o82vo635wofxwnu5iarccdusx primary key (id);
alter table base.course_directors add constraint uk_e3nnjcbf3esj437l6tj2tqt5r unique (course_id);
alter table base.course_hours add constraint pk_euy5bifeg4jalgolkkxa21w3f primary key (id);
alter table base.course_hours add constraint uk_q38fksieo0xpcfye7etmfd6rj unique (course_id,nature_id);
alter table base.course_journal_hours add constraint pk_s8496i9wb7uknu72vs44i8dx7 primary key (id);
alter table base.course_journal_hours add constraint uk_ke2wt12wi4g02ypp3i7med47s unique (journal_id,nature_id);
alter table base.course_journals add constraint pk_do83gjyf4jjoo7724iwkd5thn primary key (id);
alter table base.course_journals add constraint uk_16iu8nblky3qtm9ani5pu7vcs unique (course_id,begin_on);
alter table base.course_journals_tags add constraint pk_oc31bgxn1cvhvmk0qm0ggi2xx primary key (course_journal_id,course_tag_id);
alter table base.course_levels add constraint pk_1mqdklheeg8p8nx65q4l3og8g primary key (id);
alter table base.course_levels add constraint uk_59cbmhw5789an69kcq0j5g9i8 unique (course_id,level_id);
alter table base.course_majors add constraint pk_j74gmuqwk6c6jtwhsb95k65mg primary key (id);
alter table base.course_profiles add constraint pk_faiglxbssjx4v3eskg2fjq6uy primary key (id);
alter table base.course_profiles_books add constraint pk_mi2bbaqlh7saryv4xvnugl2du primary key (course_profile_id,textbook_id);
alter table base.course_textbooks add constraint pk_g7q36h5ul3cxttlc4n44ko4yy primary key (id);
alter table base.course_units add constraint pk_9eybgcnr9huwt9f43c30xud1m primary key (id);
alter table base.courses add constraint pk_1lyj037fss3plmcutpx9b4r2x primary key (id);
alter table base.courses add constraint uk_thp7tiw1cr1mvm9uy21fqflch unique (project_id,code);
alter table base.courses_categories add constraint pk_6yk45p39vdpsewkckbdykwte0 primary key (course_id,course_category_id);
alter table base.courses_tags add constraint pk_46nuykr92j7qtyny8dwsa0dbl primary key (course_id,course_tag_id);
alter table base.departments add constraint pk_njmudssqklm265fj3qxrl6v4i primary key (id);
alter table base.departments add constraint uk_blem78dvbmeuekoy0jg6px6j7 unique (school_id,code);
alter table base.departments_campuses add constraint pk_hayeukvl4wxa5t4wj8u012cvy primary key (department_id,campus_id);
alter table base.devices add constraint pk_q34m206q6wm6qh5d14b281wo9 primary key (id);
alter table base.experiments add constraint pk_9bocam72pq84nbf7q7r1jn5py primary key (id);
alter table base.experiments add constraint uk_4t6s3rhpyuivur62lwcyy7ul5 unique (course_id,code);
alter table base.extern_schools add constraint pk_nj2mnlh45jh2wagd9heuq58dl primary key (id);
alter table base.extern_students add constraint pk_8omlfu3itguya4lmcd6pxe0wd primary key (id);
alter table base.grades add constraint pk_tfax6erblyil71kws4l93yhnv primary key (id);
alter table base.grades add constraint uk_enpnepu169ecfvnnni3oayeva unique (project_id,code);
alter table base.graduate_seasons add constraint pk_ajyxkx6bgsd5hh3tst2x0qrs0 primary key (id);
alter table base.graduate_seasons add constraint uk_q1npfkscf2dd26j0ie8sdlvl unique (project_id,code);
alter table base.graduates add constraint pk_861dttwawbactk5wx2pb5sfg1 primary key (id);
alter table base.graduates add constraint uk_fjm29o037eumvq25eojdp797r unique (std_id);
alter table base.holidays add constraint pk_o7r9qruakt8wxjndgnml60u7r primary key (id);
alter table base.lab_centers add constraint pk_nayypwvu5gso83w6ayoe7evdh primary key (id);
alter table base.lab_centers_departs add constraint pk_h83hwmcma7e7r5uvxrj1jq9te primary key (lab_center_id,department_id);
alter table base.laboratories add constraint pk_217f1ui65li444828qnn85h1d primary key (id);
alter table base.laboratories add constraint uk_2quxs44337ol9rk7t7g6x5pha unique (school_id,code);
alter table base.major_direction_journals add constraint pk_epr9yial7hpq4n2yy22rml1lo primary key (id);
alter table base.major_directions add constraint pk_8ycvdrneuxk41hltfovvqwjk7 primary key (id);
alter table base.major_directions add constraint uk_7e936erdiet32yvrdfrgwfpyj unique (project_id,code);
alter table base.major_directors add constraint pk_skyonycb55y9ngjieh4fek3ny primary key (id);
alter table base.major_disciplines add constraint pk_oifn3upq6ylafj81hb805ut1l primary key (id);
alter table base.major_graduate_objectives add constraint pk_9vsi3kqu370binsnsslgg2us5 primary key (id);
alter table base.major_journals add constraint pk_7gepwk5lg9b0ixt7ww2tum8gm primary key (id);
alter table base.majors add constraint pk_p9yolyf8gx5n3i5kh4utj6klv primary key (id);
alter table base.majors add constraint uk_8vnop0jo5r3n5lvausdjy13aj unique (project_id,code);
alter table base.mentors add constraint pk_b2barjxncjg1kb2ilm8dw1r3s primary key (id);
alter table base.mentors add constraint uk_4n9545nrhwav5b96nw9k2di1t unique (staff_id);
alter table base.mentors_projects add constraint pk_p14hk70e30r9eyqy9ol7jn5xm primary key (mentor_id,project_id);
alter table base.minor_majors add constraint pk_puyx3wltdpl9vv77rj77l9txc primary key (id);
alter table base.officials add constraint pk_qvktne4gnlja38gqv0dh07sgx primary key (id);
alter table base.people add constraint pk_25uwl12dj9en3iflug9w23r1q primary key (id);
alter table base.presidents add constraint pk_cbv4hxj91u02s00no22yukttx primary key (id);
alter table base.project_codes add constraint pk_h8pb4rkgymaq67flwfvm8mdvg primary key (id);
alter table base.project_properties add constraint pk_rfrpbcb39anra9nb0a5x1g6dd primary key (id);
alter table base.project_properties add constraint uk_1kgy8wfyw9wg1e28k8seg64se unique (project_id,name);
alter table base.projects add constraint pk_68i13lhb2otxe0ptivfl1qpeh primary key (id);
alter table base.projects add constraint uk_clujw4wu21d33ssgde022aymk unique (code);
alter table base.projects_campuses add constraint pk_cxhgbnp68mvn8mhg6wpa8po7j primary key (project_id,campus_id);
alter table base.projects_departments add constraint pk_c3pws6toenjk026awpmfjnul6 primary key (project_id,department_id);
alter table base.projects_edu_types add constraint pk_dbq66x3eva45j6uofa2qrre3n primary key (project_id,education_type_id);
alter table base.projects_levels add constraint pk_f8wpx8th02k4kus25oq36p79n primary key (project_id,education_level_id);
alter table base.projects_std_labels add constraint pk_gpnc9xr0cnwkqao6sq7arohpc primary key (project_id,std_label_id);
alter table base.projects_std_types add constraint pk_8rp3u9k569jpshgo6y2unauns primary key (project_id,std_type_id);
alter table base.rooms add constraint pk_nsj160cru1j6fbgp9le397om7 primary key (id);
alter table base.rooms add constraint uk_b5l9ebt0gr0vn3qv9qtl0ii71 unique (school_id,code);
alter table base.school_lengths add constraint pk_dy2p1op9w9eh33o0jks159fxe primary key (id);
alter table base.school_years add constraint pk_r2s3qxwae2iuu16m6foo51mci primary key (id);
alter table base.schools add constraint pk_rb90lq0thr3gqpksvhme60v6r primary key (id);
alter table base.schools add constraint uk_m5x8j64nhdcprk9ghc6622swx unique (code);
alter table base.secretaries add constraint pk_odcqp0n1ah7oa1cwl4qtwvn9a primary key (id);
alter table base.secretaries_projects add constraint pk_357if8u51k232ik8fttkgq0j1 primary key (secretary_id,project_id);
alter table base.semester_stages add constraint pk_g7yquh6x73a5obad6ie8qwso8 primary key (id);
alter table base.semesters add constraint pk_7x6cesd88ki649j15p748hfl0 primary key (id);
alter table base.semesters add constraint uk_kd2xc25i3147f18f3i02rkisg unique (calendar_id,code);
alter table base.squads add constraint pk_flc1bpx9eojc9pwda23uoujej primary key (id);
alter table base.squads add constraint uk_6pm1jee6jdt4ynlnllhpj59f2 unique (project_id,code);
alter table base.staff_profiles add constraint pk_qhyynhx18vx1bi91rhlxlunkb primary key (id);
alter table base.staff_profiles add constraint uk_ocmcnctnhlbe30lj7wwi7c4ks unique (staff_id);
alter table base.staff_titles add constraint pk_c3kp7wxy16bvr5wxt7qo0nk2d primary key (id);
alter table base.staffs add constraint pk_qi7hj56hag2uu4e5eu4egoxrl primary key (id);
alter table base.staffs add constraint uk_ksaq070k32jb6aey065dd9xv0 unique (school_id,code);
alter table base.student_states add constraint pk_4qvivd9quhlhb7ft0dsewhsnt primary key (id);
alter table base.student_tutors add constraint pk_660n5gg3o56ge0nyioh2nu33i primary key (id);
alter table base.students add constraint pk_dp1c3lp7694lu2ri6rfh6n7g8 primary key (id);
alter table base.students add constraint uk_50fnp38f8oyhuolhke7nu920t unique (code,project_id);
alter table base.students_labels add constraint pk_ramuktutb3f32cwgsbe0apovk primary key (student_id,std_label_id,std_label_type_id);
alter table base.teachers add constraint pk_k6sh5di4vpqtsxxvusqlb0vg5 primary key (id);
alter table base.teachers add constraint uk_hwllts0elb03lqv7yenjhk3dt unique (staff_id);
alter table base.teachers_campuses add constraint pk_4wtyv7xyavsa0tlo5g8rl0txy primary key (teacher_id,campus_id);
alter table base.teachers_projects add constraint pk_ksmq83maw97gk85mth4s2g99n primary key (teacher_id,project_id);
alter table base.teaching_offices add constraint pk_cqhu9i1m9mg4ekr9tuv58c744 primary key (id);
alter table base.teaching_offices add constraint uk_90yrmn6u3xmkpyo348xl31ihq unique (project_id,code);
alter table base.textbooks add constraint pk_8fiuofquw103fs3v8kkco0orm primary key (id);
alter table base.theses add constraint pk_pm8dei1ncn39xbda439mpqao7 primary key (id);
alter table base.theses add constraint uk_2bybvwu388u4f0mo9cw49nkwe unique (std_id);
alter table base.time_settings add constraint pk_c883txidvf5q332sj20l5n5fx primary key (id);
alter table base.tutor_journals add constraint pk_32owy21iwr7ww8f1c3jvg1sbf primary key (id);
alter table base.tutor_majors add constraint pk_ox9qxt7x077f85q0wtepv4abq primary key (id);
alter table base.tutor_majors_directions add constraint pk_6pqyqlrugulyv0it8b4txbyap primary key (tutor_major_id,direction_id);
alter table base.user_group_members add constraint pk_5d31qxmuo9ojas4mdpbus7se4 primary key (id);
alter table base.user_group_members add constraint uk_6d0ao0fduegrwrn87d89nvkj7 unique (group_id,user_id);
alter table base.user_groups add constraint pk_it5g3etsarg9hkfu7e664rw1b primary key (id);
alter table base.user_groups add constraint uk_n3w9nvii9wui5ldmpdvtyooe1 unique (school_id,code);
alter table base.users add constraint pk_i4mlr3lp5ixml05sx2wuk8kp8 primary key (id);
alter table base.users add constraint uk_rtwk6iqyuv8d7se1gkkumd948 unique (school_id,code);
alter table base.versions add constraint pk_kn37tnh6h9broruk4q2gsyyip primary key (id);
alter table cfg.edu_capacity_factors add constraint pk_svrnfofl3ds355csgefiyf0s8 primary key (id);
alter table cfg.edu_cert_exempt_configs add constraint pk_25ogrkq3scobs3rr6jvtx7j01 primary key (id);
alter table cfg.edu_cert_exempt_configs_levels add constraint pk_tf2xqvguag0l8xh1e8khnwgux primary key (cert_exempt_config_id,education_level_id);
alter table cfg.edu_cert_exempt_courses add constraint pk_8vtdq21yu199uqukr5u4qgr2n primary key (cert_exempt_setting_id,course_id);
alter table cfg.edu_cert_exempt_settings add constraint pk_bvnsnltdgqpnel6hg2wa8bl6s primary key (id);
alter table cfg.edu_cert_signup_configs add constraint pk_ifi79764glfik2b7auy55mucv primary key (id);
alter table cfg.edu_cert_signup_exclusives add constraint pk_t5s02uj9t8c9q7kxg7itbqam5 primary key (cert_signup_setting_id,certificate_id);
alter table cfg.edu_cert_signup_scopes add constraint pk_78sh49aebqqecr73d449nj7fa primary key (id);
alter table cfg.edu_cert_signup_settings add constraint pk_cakh1me82ck12w2beinktj169 primary key (id);
alter table cfg.edu_exam_alloc_settings add constraint pk_jx9fvbxw2mt1y3pcb1axj0wh8 primary key (id);
alter table cfg.edu_exam_defer_settings add constraint pk_3q2pcggd70a60qvuei1nyi4vl primary key (id);
alter table cfg.edu_factor_segments add constraint pk_6jhqow1nyqkq8bomfi4pa4bs1 primary key (id);
alter table cfg.edu_grade_input_switches add constraint pk_sipio4c1axlo0u1aps51brdkx primary key (id);
alter table cfg.edu_grade_input_switches_types add constraint pk_ha7tebsm4ds67bcc3pd4vjuv2 primary key (grade_input_switch_id,grade_type_id);
alter table cfg.edu_grade_rate_configs add constraint pk_43r3gq2u9mxeo8vnat53p96kn primary key (id);
alter table cfg.edu_grade_rate_items add constraint pk_bl6jfoa15bivbeyy7bp965w81 primary key (id);
alter table cfg.edu_room_apply_depart_rooms add constraint pk_qipdsh9c69rotfatomryk6tpb primary key (room_apply_depart_scope_id,classroom_id);
alter table cfg.edu_room_apply_depart_scopes add constraint pk_h2vnbajvln52auo26uwsbd5s7 primary key (id);
alter table cfg.edu_room_apply_reserved_times add constraint pk_3u92nu8ycsxxvd4f6vb7u35e1 primary key (id);
alter table cfg.edu_room_apply_settings add constraint pk_iup28tmtsr5rdo12mqxwjetjj primary key (id);
alter table cfg.edu_schedule_setting_departs add constraint pk_1j3pnliwolxppebfq88n5r6i2 primary key (id);
alter table cfg.edu_schedule_settings add constraint pk_4m049ge32ldi4uglemj34w77d primary key (id);
alter table cfg.edu_transcript_templates add constraint pk_m87tyokii4burhxl6mcqok1a2 primary key (id);
alter table cfg.prac_ability_credit_configs add constraint pk_q7ppm0ehkq9web8a8gyhbsmxg primary key (id);
alter table cfg.prac_ability_credit_configs_levels add constraint pk_phhxtljaprkioq86sfhc5ltto primary key (ability_credit_config_id,education_level_id);
alter table cfg.prac_ability_credit_settings add constraint pk_nmkfo90wlehg370nok9dlyeln primary key (id);
alter table cfg.prac_ability_credit_settings_departs add constraint pk_rrijg4or8b4gim6fnogh8q4vj primary key (ability_credit_setting_id,department_id);
alter table cfg.prac_ability_credit_settings_majors add constraint pk_sulshfuifdasduxm70lnvxx1r primary key (ability_credit_setting_id,major_id);
alter table cfg.qos_feedback_switches add constraint pk_b7whkf51jgmhbp82phl3dt2hr primary key (id);
alter table cfg.qos_std_evaluate_switches add constraint pk_81sba75u2yf8yhm3tjcyrsns primary key (id);
alter table cfg.std_alter_configs add constraint pk_t4k7jtdpx19lrf2n1vqu73gth primary key (id);
alter table cfg.std_archive_doc_settings add constraint pk_euy7kdgak01xqyafjoxogbjo2 primary key (id);
alter table cfg.std_audit_settings add constraint pk_1tmso8l97p7jm20tsc4ua4y3x primary key (id);
alter table cfg.std_audit_settings_levels add constraint pk_dy465bk4jkltlc3rxdeupjame primary key (audit_setting_id,education_level_id);
alter table cfg.std_register_sessions add constraint pk_ofhf9115x2ra5xlq0vxmx13t5 primary key (id);
alter table cfg.std_spa_coupons add constraint pk_2vlrdsext43mu1iey1kobiccd primary key (id);
alter table cfg.std_spa_doc_settings add constraint pk_cjg9tc1r9yaj1nunfa7l8axhx primary key (id);
alter table cfg.std_spa_print_configs add constraint pk_qc425rtk3ppeeo6a3xex6f1kt primary key (id);
alter table cfg.std_transfer_options add constraint pk_kjwut08vmlyklxegooc1nftgo primary key (id);
alter table cfg.std_transfer_schemes add constraint pk_3ccwikukhp020f3uwobm76b0b primary key (id);
alter table cfg.std_transfer_scopes add constraint pk_3kj34q98ib4bmssbl2n33jqww primary key (id);
alter table cfg.std_transfer_scopes_grades add constraint pk_8em7ugqxysbj9ftc3tn2wwfvn primary key (transfer_scope_id,value_);
alter table cfg.std_transfer_scopes_majors add constraint pk_ens0r0ptm7qgcdo1hkkkkoded primary key (transfer_scope_id,major_id);
alter table cfg.std_tuition_configs add constraint pk_1dxvmk5aqbmc4h23c2e25ed9o primary key (id);
alter table code.academic_levels add constraint pk_q51xfy75i97otjcrinh3ioojl primary key (id);
alter table code.academic_levels add constraint uk_h35t9eht6ihmhsi6ttx0xu5u0 unique (code);
alter table code.activity_types add constraint pk_cmb1g96s43erp3tu63b3t5c3r primary key (id);
alter table code.activity_types add constraint uk_40dp7vraisnxtj04mahsegm5f unique (code);
alter table code.admission_types add constraint pk_a6q355jjrx7gsqp1gfus8kc09 primary key (id);
alter table code.admission_types add constraint uk_s7tnd3ykp7egjddmrhm6hgkdv unique (code);
alter table code.blood_types add constraint pk_s815d9t06dbnd8qc42j9cmbiy primary key (id);
alter table code.blood_types add constraint uk_cw185pu60enlogx4catcnx4x4 unique (code);
alter table code.book_award_types add constraint pk_sp9cov5mhwsjgxa1vqprr1opx primary key (id);
alter table code.book_award_types add constraint uk_bmuou3h9n3eql52ix5srm5cm0 unique (code);
alter table code.book_categories add constraint pk_lkbpdt3molrx8lrsafy7ter00 primary key (id);
alter table code.book_categories add constraint uk_kvn03vqif4d5kvwwdm002an9j unique (code);
alter table code.book_types add constraint pk_fw4f43brmqed51jhonpo6kc1r primary key (id);
alter table code.book_types add constraint uk_bu6h6nn9hx6ns9ujc99of3rmb unique (code);
alter table code.building_types add constraint pk_9fv09o2b3rsbo9ynt7ik8coj1 primary key (id);
alter table code.building_types add constraint uk_68npuqi7xnxjvprta4p402413 unique (code);
alter table code.certificate_categories add constraint pk_qhwrswgo8sbr37lfry41n9vn6 primary key (id);
alter table code.certificate_categories add constraint uk_oh5vjbhf5wqjqj56dk0gb4h0p unique (code);
alter table code.certificates add constraint pk_72jvjm56lmlxv2bscp1j4opmj primary key (id);
alter table code.certificates add constraint uk_mkx2966u5d4brh13s2rh5qubj unique (code);
alter table code.classroom_types add constraint pk_jqhkc4fgq6xtd8q45034q62h9 primary key (id);
alter table code.classroom_types add constraint uk_jnbxj0dxvs5hlql3nfr0x87b3 unique (code);
alter table code.clazz_archive_docs add constraint pk_rdl7dyua7mq986uedf1tuo1sg primary key (id);
alter table code.clazz_archive_docs add constraint uk_19qhsalo7xubo3jutx8o5htmh unique (code);
alter table code.clazz_tags add constraint pk_7s2u2syjpg69gecn2ei2l4a37 primary key (id);
alter table code.clazz_tags add constraint uk_9de4r9wq9x1xubugtm1nhicos unique (code);
alter table code.compatriot_types add constraint pk_72f3nrjp1nlnvxqku2roeb22x primary key (id);
alter table code.compatriot_types add constraint uk_cvym46ixfc8otn8b8ijmn1g12 unique (code);
alter table code.countries add constraint pk_d8ehdli05dbs8aiu5yxq6ek0a primary key (id);
alter table code.countries add constraint uk_5dhgnik9p8t72kaktdb8kd8dt unique (code);
alter table code.course_ability_rates add constraint pk_ixp9hq9d3g6ggc30g8py4poq5 primary key (id);
alter table code.course_ability_rates add constraint uk_ihcloqdo5h0okf4jchujnfilv unique (code);
alter table code.course_ability_subjects add constraint pk_l1poef4qsh7ebwdgv3uxkfkif primary key (id);
alter table code.course_ability_subjects add constraint uk_fu4x4wggce13plvehho1gtlpi unique (code);
alter table code.course_award_categories add constraint pk_6pmqguebdtvjxivt8hqmxfyaa primary key (id);
alter table code.course_award_categories add constraint uk_2b1aggre0kouucl9x8rc54p57 unique (code);
alter table code.course_award_types add constraint pk_m0n8wfi3rt5detkp55foa7nxp primary key (id);
alter table code.course_award_types add constraint uk_brsg073sqnh28tt27cfoke6jy unique (code);
alter table code.course_categories add constraint pk_oqysoxcp8dqo4wmygpdpatqu4 primary key (id);
alter table code.course_categories add constraint uk_2f852vsgkix9h35aukbasxq0x unique (code);
alter table code.course_category_dimensions add constraint pk_qx35190x8nbbv5p2u2x4obn8j primary key (id);
alter table code.course_category_dimensions add constraint uk_itjwhqnqcserqfrssyuemcj3w unique (code);
alter table code.course_modules add constraint pk_980xisiiqjohylc8kw96antk2 primary key (id);
alter table code.course_modules add constraint uk_fg6kojr9d970f6o6v5rx9bod unique (code);
alter table code.course_natures add constraint pk_qmyas7mib2hjnqnj6ogbi2n7p primary key (id);
alter table code.course_natures add constraint uk_rw1hkv2df9qb30k705iwphq58 unique (code);
alter table code.course_ranks add constraint pk_4vta14i320j1pgah3fdytr3sd primary key (id);
alter table code.course_ranks add constraint uk_ogoy8l02n66ogmy9avptu6hl8 unique (code);
alter table code.course_tags add constraint pk_satpi3byt6c5baol3b5m090dh primary key (id);
alter table code.course_tags add constraint uk_kcx6hro48hdaiu9hukowtnkuo unique (code);
alter table code.course_take_types add constraint pk_qkahh6b0jdyhg34u94jvoqseo primary key (id);
alter table code.course_take_types add constraint uk_fgwbxogl105wdygubia4x0ak6 unique (code);
alter table code.course_types add constraint pk_30stnnqhnpw79pr0yyslpql58 primary key (id);
alter table code.course_types add constraint uk_fngi9siu21ndq00kc435oj2go unique (code);
alter table code.day_parts add constraint pk_smmdo7fq2ewnj1lx98wxxdq91 primary key (id);
alter table code.day_parts add constraint uk_n758xomdiif4e0txke6wsnh96 unique (code);
alter table code.degree_levels add constraint pk_fiqbw5nsr2mw36xoxhj1j2116 primary key (id);
alter table code.degree_levels add constraint uk_paatawgj9c6hs54qs3gbglvj6 unique (code);
alter table code.degrees add constraint pk_2v97ef4fui6mhritxr8eaanvd primary key (id);
alter table code.degrees add constraint uk_3wc34egir46fjb9eu1acggkj5 unique (code);
alter table code.department_categories add constraint pk_mf4to82tja75w579ae7netvca primary key (id);
alter table code.department_categories add constraint uk_1267ypqnna5uxvk1p0wl2fuh8 unique (code);
alter table code.device_types add constraint pk_av3t8mqkliomcbnbg38tcllfe primary key (id);
alter table code.device_types add constraint uk_pp5sfw4fjv6fyc6wglgok63ap unique (code);
alter table code.difficulty_causes add constraint pk_lq6iocryw9m7olt9euio0caju primary key (id);
alter table code.difficulty_causes add constraint uk_buabmyat6a2sviii2q5liikbl unique (code);
alter table code.difficulty_degrees add constraint pk_a4fi6imv2vy8ddql3he4ayuc primary key (id);
alter table code.difficulty_degrees add constraint uk_5fox8obj9j7c0qvwojfdoqqks unique (code);
alter table code.discipline_catalogs add constraint pk_ldh031tie4eg35sgutxwnqorn primary key (id);
alter table code.discipline_catalogs add constraint uk_1279dmr4pp7umw94eavqlr4il unique (code);
alter table code.discipline_categories add constraint pk_rnaagxursry83nehmsmy5wj87 primary key (id);
alter table code.discipline_categories add constraint uk_smxy3kfhfpgwy542xeyt24rym unique (code);
alter table code.disciplines add constraint pk_dxv54dx9an08euovln6cd5s4x primary key (id);
alter table code.disciplines add constraint uk_osah0lag5rsel21i6uu1gqixb unique (code);
alter table code.divisions add constraint pk_ckagbn1mtjluopfx7m4ddosoi primary key (id);
alter table code.divisions add constraint uk_hccml8hpwk506p2l66y8tg1ki unique (code);
alter table code.duty_grades add constraint pk_sl8vmsl3f1jfpwosg32bccq9u primary key (id);
alter table code.duty_grades add constraint uk_faqn3nsn6cpyhtgwljnq6f4mo unique (code);
alter table code.duty_types add constraint pk_rlhgyb1b3q18kigee1df4kde6 primary key (id);
alter table code.duty_types add constraint uk_mkju5mr9eblx404xkv3dhockf unique (code);
alter table code.edu_categories add constraint pk_7p50hi0fsqia82miiqrf6ldas primary key (id);
alter table code.edu_categories add constraint uk_39n65oi32jiuycaqsvesys3ek unique (code);
alter table code.education_degrees add constraint pk_k83kie42e7dp161rew35xyojq primary key (id);
alter table code.education_degrees add constraint uk_shx6ottwax2nmo1rw58u78bkl unique (code);
alter table code.education_levels add constraint pk_nqts5vnrhlor1x9p5xk5p8dsv primary key (id);
alter table code.education_levels add constraint uk_7g26adhgvuu97atuy1j8x79um unique (code);
alter table code.education_modes add constraint pk_riccou6iptrw79s4j9rh1r2ne primary key (id);
alter table code.education_modes add constraint uk_sefk02fm6l1jly10imshq5p9i unique (code);
alter table code.education_results add constraint pk_r5o2htr643q9k2keiote10x13 primary key (id);
alter table code.education_results add constraint uk_42ltpdxra5laem73s06676wol unique (code);
alter table code.education_types add constraint pk_m95dmly9i2drstg3oebpkjybp primary key (id);
alter table code.education_types add constraint uk_fyos3e22eyhws7nvx2eq17mgw unique (code);
alter table code.election_modes add constraint pk_fe9eki74ur0gxgx89lk8y8vsc primary key (id);
alter table code.election_modes add constraint uk_e1svykmcg99gw7si27h9xrc7p unique (code);
alter table code.employ_types add constraint pk_9cdwwv62b6hnp2ci6f3os4eoo primary key (id);
alter table code.employ_types add constraint uk_q0rd5okmcshdcors7iu8b46tp unique (code);
alter table code.enroll_modes add constraint pk_obbn5syxqvad6epidl17icyh9 primary key (id);
alter table code.enroll_modes add constraint uk_j3e78icm5cskq84oufww3hnyk unique (code);
alter table code.exam_defer_reasons add constraint pk_kamdjbmhxhefplh32bbslqbei primary key (id);
alter table code.exam_defer_reasons add constraint uk_a163soi3n0flqmw3idgohok2g unique (code);
alter table code.exam_forms add constraint pk_4o5nmb6jnnouf32b3fc53ts8n primary key (id);
alter table code.exam_forms add constraint uk_q7mk62ugd1gdajtvbxt2py6b0 unique (code);
alter table code.exam_modes add constraint pk_3d9q7b2ojv9amkt3csmo82ams primary key (id);
alter table code.exam_modes add constraint uk_r6joowy1dni4gljtoe92v2uhs unique (code);
alter table code.exam_statuses add constraint pk_m4l6snovqru1ghupjbjld8qft primary key (id);
alter table code.exam_statuses add constraint uk_jkwl9gx5i72i9xkycc76x68so unique (code);
alter table code.exam_types add constraint pk_esav3g3q2ahu0i1l9d8g0k99y primary key (id);
alter table code.exam_types add constraint uk_b45j7kamdkrhm9qd2ufgbiyfl unique (code);
alter table code.experiment_categories add constraint pk_kcu5rbl4kuot4icst1glh5167 primary key (id);
alter table code.experiment_categories add constraint uk_hlkv8756ovpp91ql6d1hsil6d unique (code);
alter table code.experiment_types add constraint pk_lsvohbd75n1t5hjvqi1ns0ice primary key (id);
alter table code.experiment_types add constraint uk_ojnotfulo4sssvhe583atg34r unique (code);
alter table code.family_categories add constraint pk_ji2x0f0kp1ggjq21mcx1f8c5d primary key (id);
alter table code.family_categories add constraint uk_1t23bsp894wnybtqv3mf5he4m unique (code);
alter table code.family_relationships add constraint pk_7hi9tb37nkn1yeaj4nr5g01d primary key (id);
alter table code.family_relationships add constraint uk_1x471cgit9jgmgjrnno32l3cn unique (code);
alter table code.fee_origins add constraint pk_pjb9g9qkf41txh2q10u0knayp primary key (id);
alter table code.fee_origins add constraint uk_e7o1bghwdfjri8pp4awwosra3 unique (code);
alter table code.fee_types add constraint pk_ehkm3mi23mhgfbmohw6keg9vg primary key (id);
alter table code.fee_types add constraint uk_qwg36jxftoi87236ypjx0jcw8 unique (code);
alter table code.foreign_book_types add constraint pk_27dwcqmg6miv7f4freg62bb4b primary key (id);
alter table code.foreign_book_types add constraint uk_sxtrrji37pli31kc5qsbqrqhy unique (code);
alter table code.genders add constraint pk_fbo2yxrjjfyqdyncfjyqmlhdb primary key (id);
alter table code.genders add constraint uk_6uwkx8yhh4w794lagv7uvnntx unique (code);
alter table code.grade_types add constraint pk_8fir0v1hr6yn19vre8j6h9ddj primary key (id);
alter table code.grade_types add constraint uk_ssv6qvkbkbx6455gsmptkc54e unique (code);
alter table code.grading_modes add constraint pk_otmdo5hmda4yu6iv5xxa07307 primary key (id);
alter table code.grading_modes add constraint uk_b97msvfxl2du5qxj3gaav8vkd unique (code);
alter table code.graduate_objectives add constraint pk_i5c9grb12fgyo5n3uo30bcs7c primary key (id);
alter table code.graduate_objectives add constraint uk_ipru1n0o561cuwyc6o0ogd3p6 unique (code);
alter table code.graduate_types add constraint pk_dy4s401v9m865dryabd1fxtn0 primary key (id);
alter table code.graduate_types add constraint uk_9die6co9800of7rw2vh6a63cr unique (code);
alter table code.health_statuses add constraint pk_ewtk7l63wlk6ptj855tfj5dfj primary key (id);
alter table code.health_statuses add constraint uk_styg2klnvn0k1w4s864ifol19 unique (code);
alter table code.household_types add constraint pk_s7op8qppo9yfud198nlanf1pi primary key (id);
alter table code.household_types add constraint uk_cnav0pni6ce5cyyxef7tqtp12 unique (code);
alter table code.hsk_levels add constraint pk_ljbtoh8dew8tptj5qj2hvw4o primary key (id);
alter table code.hsk_levels add constraint uk_gtvnlv6mjjmcdwgh17ltrqqlt unique (code);
alter table code.id_types add constraint pk_4yqih3x42nqjh4tigc0evwlgm primary key (id);
alter table code.id_types add constraint uk_beex3aqbbv2nqkicpjadtdvdv unique (code);
alter table code.institution_categories add constraint pk_fd9fbuxbvexuhcw9jfsvrvdtp primary key (id);
alter table code.institution_categories add constraint uk_k5ar1dxviaioiewl76ct7jlga unique (code);
alter table code.institutions add constraint pk_bfw2t7ynqlyotm6eyi4dwgtk9 primary key (id);
alter table code.institutions add constraint uk_90wcwrx6ap068pspum25xhtyu unique (code);
alter table code.job_statuses add constraint pk_na0xycictcofkatnh5glv8day primary key (id);
alter table code.job_statuses add constraint uk_k02k1s3sjqc9v9dvqrarjgc1c unique (code);
alter table code.language_abilities add constraint pk_qo5m05jp2cqjyioi5cll8fgar primary key (id);
alter table code.language_abilities add constraint uk_6p3nor27f0i5e8ryfh5ppa9un unique (code);
alter table code.languages add constraint pk_sdlywiif4qur2robjmciupw07 primary key (id);
alter table code.languages add constraint uk_myc139vxcejowe4q8qm3ca5jn unique (code);
alter table code.level1_disciplines add constraint pk_6kymaieloxnmdimt05r4bie0q primary key (id);
alter table code.level1_disciplines add constraint uk_oc1wjadmqun61ry6dba697cwm unique (code);
alter table code.marital_statuses add constraint pk_gq36i33myef28ldxfx4mjb2nl primary key (id);
alter table code.marital_statuses add constraint uk_8p2hd9frpqs2fbulxhe8mtskj unique (code);
alter table code.nations add constraint pk_jae4hw2gt1sx4epxwbdkx3c12 primary key (id);
alter table code.nations add constraint uk_791yx3rdfmeevupxwptmm30o3 unique (code);
alter table code.passport_types add constraint pk_gtg10x4u17ikg4x2fxlyxmgdy primary key (id);
alter table code.passport_types add constraint uk_10c0292fifdx77x100dtk2ho2 unique (code);
alter table code.political_statuses add constraint pk_7xjjklfwlo69nyhtpoe3qx1sw primary key (id);
alter table code.political_statuses add constraint uk_2giyhgqrhixando5e6pkr48of unique (code);
alter table code.post_grades add constraint pk_lp7fwnrpynows9qmxo6uld7nb primary key (id);
alter table code.post_grades add constraint uk_6mcnlu55dfti3itsiig9s36p unique (code);
alter table code.post_types add constraint pk_4o6w1x4djydd1nskoh52mjr02 primary key (id);
alter table code.post_types add constraint uk_5ll10mqocole6bnix353h3w2b unique (code);
alter table code.prac_activity_types add constraint pk_1280lnc80k9gw3rpx92i02qhp primary key (id);
alter table code.prac_activity_types add constraint uk_7b25q1acdimewk5onml28197d unique (code);
alter table code.press_grades add constraint pk_njmxmuicw8foumieqgjnko6cy primary key (id);
alter table code.press_grades add constraint uk_tetfawlge4670eycic2edwetv unique (code);
alter table code.presses add constraint pk_rk7ek6u5edrwv9xxydg7bc48q primary key (id);
alter table code.presses add constraint uk_8idhuopnq9vabab63pyqfqir6 unique (code);
alter table code.professional_grades add constraint pk_23d8s972h76b0xdatjfcxupe1 primary key (id);
alter table code.professional_grades add constraint uk_j783ewxhftk3q9ixbyavljn5j unique (code);
alter table code.professional_titles add constraint pk_cjq04j9bh6xleeky128k1gswt primary key (id);
alter table code.professional_titles add constraint uk_bncxdgi5xdsp50jnrwvyii5yg unique (code);
alter table code.program_course_tags add constraint pk_mxsf2utw2s5dh63wx9s44pf4n primary key (id);
alter table code.program_course_tags add constraint uk_ieqp9ajuh1804wlmmjhwjentb unique (code);
alter table code.publication_grades add constraint pk_r45qdwy0e7li10q5re3sfi8uf primary key (id);
alter table code.publication_grades add constraint uk_5cwt30wjytp7kqqxxg9mgciql unique (code);
alter table code.publications add constraint pk_posqs7doguprjnunmq0nhxbvh primary key (id);
alter table code.publications add constraint uk_ojr6l8tqoupm6dq3els21esn unique (code);
alter table code.railway_stations add constraint pk_mwpmgne9kbs3rqkr9yimeky4b primary key (id);
alter table code.railway_stations add constraint uk_liaskyn9dcenlbxc2p3sjlr6h unique (code);
alter table code.rd_award_grades add constraint pk_ij1rtygc537ykj7n9n0fonlm primary key (id);
alter table code.rd_award_grades add constraint uk_6i8kdj7snafxjqhed4wm4nwn7 unique (code);
alter table code.rd_levels add constraint pk_oblsjsi7q9bdeq4kxmf4j3qc9 primary key (id);
alter table code.rd_levels add constraint uk_5bw4yswj1h9pyo86b0wrm1f09 unique (code);
alter table code.religions add constraint pk_db95knst6ss1grofhc0kkrap4 primary key (id);
alter table code.religions add constraint uk_rmojysk9alhr0ih800fyw2af unique (code);
alter table code.room_types add constraint pk_jru03m3vn58qmif6k5urq2y6s primary key (id);
alter table code.room_types add constraint uk_pwg4oqr4ylc28g701vfys5hc4 unique (code);
alter table code.social_unit_types add constraint pk_jt9a7ljhk01bsevoj0qbjw2y3 primary key (id);
alter table code.social_unit_types add constraint uk_bc5712vn0ag3o2gbjb8jx7hbu unique (code);
alter table code.staff_source_types add constraint pk_jsm380evxdo115plu90m5dmtc primary key (id);
alter table code.staff_source_types add constraint uk_jy2k3tq0rnovx9qni4hbo3ear unique (code);
alter table code.staff_types add constraint pk_a4368uis6hkcnv1jksw7hntap primary key (id);
alter table code.staff_types add constraint uk_gwihxgl4bspt7wg34tfsln42t unique (code);
alter table code.std_alter_reasons add constraint pk_33wxn4eyascc7730eqdyu8nap primary key (id);
alter table code.std_alter_reasons add constraint uk_d61fcrrbis8g296gvq0aoswdw unique (code);
alter table code.std_alter_types add constraint pk_8eujmk9iw3oyow6csjap0m3jm primary key (id);
alter table code.std_alter_types add constraint uk_d0hmv5idntvp604d8rv5ffwn1 unique (code);
alter table code.std_doc_types add constraint pk_504qg1oldgtxqm3nb3cbtuye7 primary key (id);
alter table code.std_doc_types add constraint uk_88xe3fjb0lxyfmaywg9ov25gk unique (code);
alter table code.std_label_types add constraint pk_2o1x04mqhbpsuu4wsb4523iy3 primary key (id);
alter table code.std_label_types add constraint uk_hryqvm8sj4a4w3fwfsg1tsjl2 unique (code);
alter table code.std_labels add constraint pk_l192yxgvwsecl9kqujivj6f59 primary key (id);
alter table code.std_labels add constraint uk_jviknlfon7h8c5sgvtbxwfpxa unique (code);
alter table code.std_practice_categories add constraint pk_plovwy97rxnw2kxt8ew0mri5s primary key (id);
alter table code.std_practice_categories add constraint uk_32haswsktuxdoii5wj30l2r8w unique (code);
alter table code.std_practice_types add constraint pk_gjdq9tpb799gj5hgk7aqw2c48 primary key (id);
alter table code.std_practice_types add constraint uk_nu2056990u2cwn9i884wcnr7m unique (code);
alter table code.std_punishment_types add constraint pk_sefi5c7gqa45cyc6o4selwcb2 primary key (id);
alter table code.std_punishment_types add constraint uk_mw835oirmjqh1xkdbfkfsrfg1 unique (code);
alter table code.std_types add constraint pk_6ant2dfueuaiqo9p6i2jkkqqf primary key (id);
alter table code.std_types add constraint uk_jm6qwf4cy0gayqcsrpddyjbey unique (code);
alter table code.student_statuses add constraint pk_r0abq98f6x7nppqxk49b1xc0 primary key (id);
alter table code.student_statuses add constraint uk_58ik22jbawb1i8ht83lk11o87 unique (code);
alter table code.study_types add constraint pk_m90ecgcdsvgkp9chbeuwwk9sk primary key (id);
alter table code.study_types add constraint uk_rp1j8oeth9sda21pk71dqp8m8 unique (code);
alter table code.syllabus_topic_labels add constraint pk_ba2qkaicpiw5oog5u9sm3d1wr primary key (id);
alter table code.syllabus_topic_labels add constraint uk_olq7lmxw1if38fl9gsmauhn0a unique (code);
alter table code.teach_lang_types add constraint pk_r34pug3nqijvuda05m4ok825n primary key (id);
alter table code.teach_lang_types add constraint uk_8whak4jl313vch6unmqvsguuc unique (code);
alter table code.teaching_forms add constraint pk_im37ftwfe3857370qito8al7d primary key (id);
alter table code.teaching_forms add constraint uk_e6dw7nu15cnb29jw939qy7o4a unique (code);
alter table code.teaching_methods add constraint pk_s2ob7rrxiu3hwv3dgtwvik47a primary key (id);
alter table code.teaching_methods add constraint uk_2oid1oma03fwmia8yeepjtaxy unique (code);
alter table code.teaching_natures add constraint pk_iidoc1hu3mfla79sh3ys7xr3c primary key (id);
alter table code.teaching_natures add constraint uk_ft2l2vqf6ue19y570m8n2jb1i unique (code);
alter table code.teaching_sections add constraint pk_docvjyxvufaf2y8wly8pqnp4d primary key (id);
alter table code.teaching_sections add constraint uk_pl7lusqa27g9jxm2rlvot4qmm unique (code);
alter table code.textbook_forms add constraint pk_51hrkbnu1nvo3wum11rlmfg41 primary key (id);
alter table code.textbook_forms add constraint uk_dmmvqtr0phm6cuy5r3bladqfk unique (code);
alter table code.thesis_topic_sources add constraint pk_3lderniukaq5dpqfvlh0qejob primary key (id);
alter table code.thesis_topic_sources add constraint uk_h0vhsaoskfugync7c9g7l9wsk unique (code);
alter table code.thesis_types add constraint pk_4tcotln8xe9p0p18p0fjqeul2 primary key (id);
alter table code.thesis_types add constraint uk_rvlh56ev01vw0s1m2727ulta3 unique (code);
alter table code.tutor_types add constraint pk_blidh1mx6m4ci11jl2xhgmhyh primary key (id);
alter table code.tutor_types add constraint uk_mvnftvqyie0v05l9t7khdnxp2 unique (code);
alter table code.uee_subject_types add constraint pk_pp8tdd0qin0qphea92v03xq69 primary key (id);
alter table code.uee_subject_types add constraint uk_9ohkri73dgrruvg1noi5cjqvm unique (code);
alter table code.uncheckin_reasons add constraint pk_b2456k7m08w83dfw2ofx5yvx primary key (id);
alter table code.uncheckin_reasons add constraint uk_erpbu68elyqcrwgi8w0suoqou unique (code);
alter table code.unregistered_reasons add constraint pk_a05jbnwecpcjh1vca74kq4u39 primary key (id);
alter table code.unregistered_reasons add constraint uk_t1sd0t3npnyfes867y9rlipbc unique (code);
alter table code.user_categories add constraint pk_g22tbnb6clymkxmi560ll33em primary key (id);
alter table code.user_categories add constraint uk_j3ynn4qkfqo4imt05sbforud3 unique (code);
alter table code.visa_types add constraint pk_5u4p2t27gbgicni5lyayh6tlv primary key (id);
alter table code.visa_types add constraint uk_3yagdiemtpdg1ohnf12cofgfs unique (code);
alter table code.whereto_goes add constraint pk_4613lax8xj9thcny8sbdbs84j primary key (id);
alter table code.whereto_goes add constraint uk_kgwluf8uj4fa2bgtefeq1ta0y unique (code);
alter table code.work_statuses add constraint pk_ia5xweu6skbop6en26o5y4jxs primary key (id);
alter table code.work_statuses add constraint uk_8iau4k90qik38mmw3v600qll6 unique (code);
alter table degree.advisors add constraint pk_i5l7e3g9bc2myekmmelts2qsv primary key (id);
alter table degree.advisors add constraint uk_jcnlieyxd426oafao9vvhfd17 unique (teacher_id);
alter table degree.advisors_departs add constraint pk_2gy4x53kvo6vxjqsof36u03gt primary key (advisor_id,department_id);
alter table degree.blind_peer_reviews add constraint pk_kgcn5gdr0f2jp8y4ytx2t83m5 primary key (id);
alter table degree.blind_peer_reviews add constraint uk_mopgj4rosykqui5vlesn90hes unique (writer_id);
alter table degree.commitments add constraint pk_2wvfrxkxbdght6kk1hnen6o7f primary key (id);
alter table degree.commitments add constraint uk_9v8ek3ll64wdbb3m9ijcasn72 unique (writer_id);
alter table degree.copy_checks add constraint pk_ojj9g6o8ajtj1lbr9d01ede1w primary key (id);
alter table degree.deadlines add constraint pk_nh4p2cwv6qeb8mg4f3mx0d5ot primary key (id);
alter table degree.defense_groups add constraint pk_c45k166wf1ysch1e1xcftiwmm primary key (id);
alter table degree.defense_infoes add constraint pk_45baqcrd3wtuqspgq9nkaj4ya primary key (id);
alter table degree.defense_infoes add constraint uk_1s0h1diq6f0dwhhqwxe6pcykk unique (writer_id);
alter table degree.defense_members add constraint pk_p3aecabp96bs1ps09le2un6x3 primary key (id);
alter table degree.defense_notices add constraint pk_guoctyvgn106iuwq59325se1o primary key (id);
alter table degree.defense_writers add constraint pk_g6nqx0uyocsmdc3pgiropyt7n primary key (id);
alter table degree.defense_writers add constraint uk_1e633rm3u83fkxi1k13kky877 unique (writer_id);
alter table degree.depart_plans add constraint pk_fosmq37orxkj5i1049jfx7y7 primary key (id);
alter table degree.depart_plans_times add constraint pk_7ge72fgm68a7os42osuub2098 primary key (depart_plan_id,begin_at,stage,end_at);
alter table degree.guidances add constraint pk_ry9cqd94w60tjega5yn5hfcgc primary key (id);
alter table degree.midterm_check_details add constraint pk_nyl6q04c7r0mr6x6jsrcrw1ra primary key (id);
alter table degree.midterm_check_details add constraint uk_8n2cq37obd973bqb9gqmarwey unique (check_id,item_id);
alter table degree.midterm_check_items add constraint pk_o9eunp3w0qjk6ot39ivv7vi92 primary key (id);
alter table degree.midterm_checks add constraint pk_ltkl47flxa7xhbfixg14oo09j primary key (id);
alter table degree.midterm_checks add constraint uk_pgwmev6yuaj7l0gqamm8q318f unique (writer_id);
alter table degree.paper_submissions add constraint pk_it7q5ku8f1k22d4rmd8nwm5yv primary key (id);
alter table degree.proposals add constraint pk_na7fgi69wfwklq4i2jw3k68n8 primary key (id);
alter table degree.proposals add constraint uk_ro29y4ytkhp4ejqadt59emj6w unique (writer_id);
alter table degree.signatures add constraint pk_1r9lk7dkhuib69tcdacov8e6 primary key (id);
alter table degree.signatures add constraint uk_ei6qbxw0vr4l2qwidxgc0yyfb unique (writer_id);
alter table degree.subject_applies add constraint pk_cx4p6gchh5wjpf6v3yh2mq5pn primary key (id);
alter table degree.subject_applies add constraint uk_9wcnvhckvqrd0mclhi4y2cbjr unique (writer_id);
alter table degree.subjects add constraint pk_trw6rmspx195oy01rpbtghlsf primary key (id);
alter table degree.subjects add constraint uk_afynx14cx8h179uyu8gnwna1h unique (season_id,name);
alter table degree.subjects_majors add constraint pk_f9uumbw2vd9v3qwx1qd4edi4f primary key (subject_id,major_id);
alter table degree.thesis_archives add constraint pk_3w21a253lbmr3pu2cqxayq301 primary key (id);
alter table degree.thesis_archives add constraint uk_6ppgmacal52hjo8831um7qon8 unique (writer_id);
alter table degree.thesis_checks add constraint pk_h3wix678400peq8mufhpn76u9 primary key (id);
alter table degree.thesis_checks add constraint uk_8vgla3u0x7jq1whmak4w9in13 unique (season_id,writer_id,degree_major_code);
alter table degree.thesis_doc_types add constraint pk_cal9ppgryp24jb153gd5cw31r primary key (id);
alter table degree.thesis_doc_types add constraint uk_lpdaqpaxb6r8my16k48gl6xa9 unique (code);
alter table degree.thesis_docs add constraint pk_tjx4cxymbuw05ywcmv3mm73cr primary key (id);
alter table degree.thesis_docs add constraint uk_fsvjnlx8r7pbk9k559q4gqh3s unique (writer_id,doc_type_id);
alter table degree.thesis_papers add constraint pk_blkbqehyo53i9cn2bqleseray primary key (id);
alter table degree.thesis_papers add constraint uk_p14pjyoels7xfyutr26h795md unique (writer_id);
alter table degree.thesis_plans add constraint pk_tn31lepw015ftlf1hgvs8a8kj primary key (id);
alter table degree.thesis_plans_times add constraint pk_k4hptnvxacg3d67447oym5lrk primary key (thesis_plan_id,begin_at,stage,end_at);
alter table degree.thesis_reviews add constraint pk_pmutuonqxs4khwic666oq6yh primary key (id);
alter table degree.thesis_reviews add constraint uk_c5o3hq18aynpl1cvaqd0bsxbl unique (writer_id);
alter table degree.writers add constraint pk_m9q0hraod30jnt738610lw24f primary key (id);
alter table degree.writers add constraint uk_ii4fkei0dohqc92kvxlbbcopw unique (std_id,season_id);
alter table edu.attendances add constraint pk_2t9o47wqtt7xk1qlypcetbjw8 primary key (id);
alter table edu.attendances add constraint uk_f49nisop8s1yky4smcdbv2f1p unique (semester_id,clazz_id,std_id);
alter table edu.audit_course_results add constraint pk_9p21ojbfpsddsa1snrmjwg301 primary key (id);
alter table edu.audit_course_results add constraint uk_l15jy8rdu4luc06vmaa8xx7ct unique (group_result_id,course_id);
alter table edu.audit_group_results add constraint pk_1gbmaroenosd2ni5ercinp1yo primary key (id);
alter table edu.audit_plan_results add constraint pk_n7ksi77x1p79dnonu72yklf7e primary key (id);
alter table edu.audit_plan_results add constraint uk_ny8kmjinja7xa9ye8cou48588 unique (std_id);
alter table edu.cert_signups add constraint pk_buvpy5j8eye2vtlladutvfisn primary key (id);
alter table edu.cert_signups add constraint uk_42lb6e60ij443kyh7o5nqapur unique (std_id,semester_id,certificate_id);
alter table edu.certificate_grades add constraint pk_21bw15677thfojwd283r42rcx primary key (id);
alter table edu.certificate_grades add constraint uk_f23otx93d7vvrx9t7jxd7bajc unique (std_id,certificate_id,acquired_in);
alter table edu.certificate_grades_exempts add constraint pk_nbymota90h5p6y4yvufp7nmea primary key (certificate_grade_id,course_id);
alter table edu.clazz_activities add constraint pk_5rankuhqjj88fbic1k8vl9ib0 primary key (id);
alter table edu.clazz_activities_rooms add constraint pk_mu2b4wc5pvt35yub2mwe0gndf primary key (activity_id,classroom_id);
alter table edu.clazz_activities_teachers add constraint pk_pikhy8td3magdbtgj9qqv6eqk primary key (activity_id,teacher_id);
alter table edu.clazz_archives add constraint pk_svxcnumv1r9p24ymun0hsdg28 primary key (id);
alter table edu.clazz_archives add constraint uk_caluyc9lm5rlj5628fenvr9a unique (clazz_id,doc_id);
alter table edu.clazz_book_stats add constraint pk_baqp1iuvt4utj5ya9hn3k8w9p primary key (id);
alter table edu.clazz_bulletins add constraint pk_qr18drp7kdfhmd4be5fgqvs2o primary key (id);
alter table edu.clazz_bulletins add constraint uk_bw61pgrg2iw0irmhs8hof0q0g unique (clazz_id);
alter table edu.clazz_docs add constraint pk_bncaja4f5dv9wyhhyhm8o8p5f primary key (id);
alter table edu.clazz_final_exams add constraint pk_s5iu9lktk5j5hcddn8hifbr8e primary key (id);
alter table edu.clazz_final_exams add constraint uk_j4vo8w3lb8v157ssmw709sga8 unique (clazz_id);
alter table edu.clazz_groups add constraint pk_rk07cifqsq9cq5cscif6rre46 primary key (id);
alter table edu.clazz_notice_files add constraint pk_tc2n52103b3130x5jaaaxj7n1 primary key (id);
alter table edu.clazz_notices add constraint pk_dhgey9skl0nde8lg46v723xi2 primary key (id);
alter table edu.clazz_plans add constraint pk_31hgwvg2869u4lvi7jah005em primary key (id);
alter table edu.clazz_plans add constraint uk_6oj32b95hin66f630cor8jvp4 unique (clazz_id);
alter table edu.clazz_programs add constraint pk_20l3sep385iuu3rtvbay24j3m primary key (id);
alter table edu.clazz_restriction_items add constraint pk_rtknsmxggkox9vw5lwm4m18us primary key (id);
alter table edu.clazz_restrictions add constraint pk_mtefxfgvvkuesed42g7edh473 primary key (id);
alter table edu.clazz_section_hours add constraint pk_gxk3t91m7do6rudnn4m962918 primary key (id);
alter table edu.clazzes add constraint pk_3ra1a077so5k9mwdt2kxb3k0b primary key (id);
alter table edu.clazzes add constraint uk_8xuvd3v6lnrq5xmcl8jje0yau unique (project_id,semester_id,crn);
alter table edu.clazzes_ability_rates add constraint pk_kx0jp80tganm39yvlc4lewj74 primary key (clazz_id,course_ability_rate_id);
alter table edu.clazzes_books add constraint pk_blgbfvis5pagursyudqrjkkaf primary key (clazz_id,textbook_id);
alter table edu.clazzes_tags add constraint pk_e1e2u69ixc5hje4f436327g1t primary key (clazz_id,clazz_tag_id);
alter table edu.clazzes_teachers add constraint pk_38x8fp2quo9ykkur4hvt7khir primary key (clazz_id,teacher_id,idx);
alter table edu.course_grade_states add constraint pk_ss5mvl6jqttk0ubobqdhdni8u primary key (id);
alter table edu.course_grades add constraint pk_1ucmwigfmllurolusv5j8d5xv primary key (id);
alter table edu.course_grades add constraint uk_xitxltysiibv3efvpe69hk1j unique (std_id,course_id,semester_id,crn);
alter table edu.course_takers add constraint pk_r9e52tj7ca5ohhmokt4nw1h8e primary key (id);
alter table edu.course_takers add constraint uk_9pqkafkcyi7pe6799lg614vay unique (std_id,course_id,semester_id);
alter table edu.course_tasks add constraint pk_t2hnkntagl4pt5brhlsq5idg7 primary key (id);
alter table edu.course_tasks add constraint uk_rp2ft51pyobp9n4y4u0hx6hso unique (semester_id,course_id,idx);
alter table edu.course_tasks_teachers add constraint pk_oj0gk5qp3paxe0shf72mu0a72 primary key (course_task_id,teacher_id);
alter table edu.exam_activities add constraint pk_1n892fv0956m99fkw49r4k5y7 primary key (id);
alter table edu.exam_activities_rooms add constraint pk_6cw1w9e67eqd2bybivya2qb8h primary key (exam_activity_id,exam_room_id);
alter table edu.exam_analyses add constraint pk_950ruvj5m4hf04gmkfwwyj9da primary key (id);
alter table edu.exam_analyses add constraint uk_5plw503n3jbjkxyi8ti9df4my unique (clazz_id);
alter table edu.exam_grade_states add constraint pk_4wy4ksg5gx6h85tb11hphty4b primary key (id);
alter table edu.exam_grade_states add constraint uk_hbbjtria5w2yv76athjignsdk unique (grade_state_id,grade_type_id);
alter table edu.exam_grades add constraint pk_kgkg3a3map061ka3c7kevp21e primary key (id);
alter table edu.exam_grades add constraint uk_ij6eu0s9mftmblpso35iwm796 unique (course_grade_id,grade_type_id);
alter table edu.exam_groups add constraint pk_sibrdqqr0ie2m6sa4x21twlpa primary key (id);
alter table edu.exam_groups_rooms add constraint pk_ajbo1jbua6vqgkiifpob0wm72 primary key (exam_group_id,classroom_id);
alter table edu.exam_notices add constraint pk_k3c8i22sc17d5t4401t51p2ql primary key (id);
alter table edu.exam_room_groups add constraint pk_8e9jvyge9pm0yll17wkms3v01 primary key (id);
alter table edu.exam_room_groups_rooms add constraint pk_jxldkkl8o0nyifobrb87n1gj2 primary key (exam_room_group_id,classroom_id);
alter table edu.exam_rooms add constraint pk_ruuyfm4i7tf18lyint9kxx1i9 primary key (id);
alter table edu.exam_takers add constraint pk_3f19qyj4dhr0r0roi7ku4dbe1 primary key (id);
alter table edu.exam_takers add constraint uk_aw5c1boicjyshvgr1tbouf4r0 unique (std_id,clazz_id,exam_type_id);
alter table edu.exam_tasks add constraint pk_kpj9d25h0k6s95j7sov5ow3ee primary key (id);
alter table edu.exam_tasks_rooms add constraint pk_2awcxprgxcvs7gi81idt6itnn primary key (exam_task_id,classroom_id);
alter table edu.exam_turns add constraint pk_7mybkgmuiw34nagg7ti6oui2b primary key (id);
alter table edu.executive_course_groups add constraint pk_1youdaxcg42qn6nhvwcbwad9g primary key (id);
alter table edu.executive_plan_courses add constraint pk_lhpe3jgx7uq87hwmc6t332mge primary key (id);
alter table edu.executive_plan_courses add constraint uk_aqtnrm89r68onugcbfp1jcbwa unique (group_id,course_id);
alter table edu.executive_plans add constraint pk_lx1yisydhsot7560t92obwfmy primary key (id);
alter table edu.exempt_courses add constraint pk_q2fwu5hjcpjwsvnda5gql38gq primary key (id);
alter table edu.exempt_courses_std_types add constraint pk_comjg7o4sak1o96o5jyca6spe primary key (exempt_course_id,std_type_id);
alter table edu.extern_exempt_credits add constraint pk_l0opvg9j48tck1shbbvl5xy1f primary key (id);
alter table edu.extern_exempt_credits add constraint uk_keyac61jtkwtkco6036lmqakh unique (std_id);
alter table edu.extern_grades add constraint pk_c6lgnfjsyt425c90aek6a4cba primary key (id);
alter table edu.extern_grades_exempts add constraint pk_1i3rqkxurk5pqwi4fjfxgqnul primary key (extern_grade_id,course_id);
alter table edu.final_makeup_courses add constraint pk_nb8vd6udx54xefb3ngrsm90f0 primary key (id);
alter table edu.final_makeup_courses_squads add constraint pk_ksgdtf4d0hu23dxxc2e6t0bl6 primary key (final_makeup_course_id,squad_id);
alter table edu.final_makeup_takers add constraint pk_eh01n7uwcd4vicj1mwrn7on3s primary key (id);
alter table edu.ga_grade_states add constraint pk_14dswddj9gfs9i2v6ep2m05ku primary key (id);
alter table edu.ga_grade_states add constraint uk_55c7tsme8v49y1o7tjn1r8vpe unique (grade_state_id,grade_type_id);
alter table edu.ga_grades add constraint pk_bvbnlqsyj55povhh0l0g94so2 primary key (id);
alter table edu.ga_grades add constraint uk_6l1n05tqq55sh661e6s1s12vm unique (course_grade_id,grade_type_id);
alter table edu.invigilation_clazz_quotas add constraint pk_21v272vaovqf9c0nuwoh1o095 primary key (id);
alter table edu.invigilation_clazz_quotas add constraint uk_99ht874j4b5ccw734m1h1moa0 unique (clazz_id,teacher_id);
alter table edu.invigilation_quota_details add constraint pk_6l5kr1v7rids4edf69va5n5lr primary key (id);
alter table edu.invigilation_quotas add constraint pk_91u61cmn1goxeqobsjde5pccq primary key (id);
alter table edu.invigilation_quotas add constraint uk_h35ysb0b74pj8foxdpfxvy0sv unique (invigilator_id,semester_id);
alter table edu.invigilation_quotas_excludes add constraint pk_i04mllgl8dh4whufiq0sw5smj primary key (invigilation_quota_id,exclude_on);
alter table edu.invigilations add constraint pk_bg0m2o403b43vb9mkg3noo1td primary key (id);
alter table edu.lesson_design_sections add constraint pk_8kppfknajixthr1k69jiv7rp3 primary key (id);
alter table edu.lesson_design_texts add constraint pk_bx15i5djo5j3acv624ecygp6i primary key (id);
alter table edu.lesson_designs add constraint pk_q7x9xap0fvw6fl1yivtswgfgq primary key (id);
alter table edu.lessons add constraint pk_fha0ldq8mchqk0d5t5xy64chj primary key (id);
alter table edu.major_alt_courses add constraint pk_scvgmvao9tsvfcm1whcnxvu3b primary key (id);
alter table edu.major_alt_courses_news add constraint pk_q055pvumg14plkk3p3dyb4v5o primary key (major_alt_course_id,course_id);
alter table edu.major_alt_courses_olds add constraint pk_tfl42phv9abi60dnauh3cgtx5 primary key (major_alt_course_id,course_id);
alter table edu.major_course_groups add constraint pk_3nxbhw8uol7n3nw0kpsdr6lvr primary key (id);
alter table edu.major_plan_courses add constraint pk_3wd4vyblbfks1j2lwty25qnbu primary key (id);
alter table edu.major_plan_courses add constraint uk_bmxrewotma5nd0dxovv1m77cw unique (group_id,course_id);
alter table edu.major_plans add constraint pk_ohol0jsnb6did1juitfw0awos primary key (id);
alter table edu.mini_clazz_activities add constraint pk_6km9ontbm925da7x6y1d0jxh6 primary key (id);
alter table edu.mini_clazzes add constraint pk_6b9ghfkpxs4254cqx2ta74dmx primary key (id);
alter table edu.mini_clazzes_stds add constraint pk_gf6ecj0anc2bodb5uq0f2jtx0 primary key (mini_clazz_id,student_id);
alter table edu.moral_grades add constraint pk_t3qyjinvsnfy0y84um9prvcmq primary key (id);
alter table edu.occupancies add constraint pk_cv4gsidr885aanuscffivwbb7 primary key (id);
alter table edu.program_course_labels add constraint pk_aejk5w39nv0dg8818jwpg67bq primary key (id);
alter table edu.program_course_outcomes add constraint pk_nvau4y9rvun2kbgatx4y0qhat primary key (id);
alter table edu.program_doc_metas add constraint pk_rt39x9dho1u8xtaov9jms7p94 primary key (id);
alter table edu.program_doc_sections add constraint pk_7f7k9q32r86m55a0r93h2uflm primary key (id);
alter table edu.program_doc_templates add constraint pk_8e5naml4u9wbcyjrrhlmeb3ay primary key (id);
alter table edu.program_doc_templates_types add constraint pk_lwfg2w960gakch3fo4djc31d7 primary key (program_doc_template_id,std_type_id);
alter table edu.program_docs add constraint pk_tmprm3sm6os3l88qop5r89q9x primary key (id);
alter table edu.program_objectives add constraint pk_ejx91beni3lkiv6q1jo7gb1qn primary key (id);
alter table edu.program_outcomes add constraint pk_ad3rhlvff93jocwu172v2ua7j primary key (id);
alter table edu.program_outlines add constraint pk_rl1nqqsx91kr0k5to4csk0hxq primary key (id);
alter table edu.program_prerequisites add constraint pk_ejooikitt3cj7onfpr7mep1tg primary key (id);
alter table edu.program_tables add constraint pk_ljn79y0w3bm6lr3nctrchnqv primary key (id);
alter table edu.program_texts add constraint pk_55uvopdrvnwndti8ayyrhpsc0 primary key (id);
alter table edu.programs add constraint pk_9osl20jg9o3ywqs65190pgm9v primary key (id);
alter table edu.programs_degree_certificates add constraint pk_4coy86rddcbvfyvyoxdone26l primary key (program_id,certificate_id);
alter table edu.programs_degree_courses add constraint pk_c56n0ogp63uo4vcl3pp16l842 primary key (program_id,course_id);
alter table edu.programs_std_types add constraint pk_9ehq0f2rhqjce1anhhw5bcf4b primary key (program_id,std_type_id);
alter table edu.regular_grade_states add constraint pk_hnj9nkhhqpuj7yg9v7efhigo6 primary key (id);
alter table edu.regular_grade_states add constraint uk_nv0dulh1dhs6ddpd0clg8tvac unique (clazz_id);
alter table edu.regular_grades add constraint pk_83v4fybspmj863btsicnyux6h primary key (id);
alter table edu.regular_grades add constraint uk_ek8kmmv077hq3rh4docowoqw7 unique (std_id,clazz_id);
alter table edu.room_applies add constraint pk_bc80rnoxs22g3i49cprrotgaq primary key (id);
alter table edu.room_applies_rooms add constraint pk_f3isa2ggycb2cyjdu9cg3ow5q primary key (room_apply_id,classroom_id);
alter table edu.room_applies_times add constraint pk_gut4id17joy6x8d5psmvc1pd2 primary key (room_apply_id,weekstate,begin_at,start_on,end_at);
alter table edu.room_available_times add constraint pk_72hrirupp9pfx9rkg0b30rct2 primary key (id);
alter table edu.room_occupy_apps add constraint pk_jhnnof3gdp1q99769e6htdi2x primary key (id);
alter table edu.schedule_suggest_activities add constraint pk_myer3gf4y362usk4aho5ppl6t primary key (id);
alter table edu.schedule_suggests add constraint pk_huj196fcrgxy8bfyiavvr2qxg primary key (id);
alter table edu.schedule_suggests add constraint uk_p580lu918uyus7rr6weynmg2i unique (clazz_id);
alter table edu.share_course_groups add constraint pk_45hb6362voxm23n8sxy3fgo3b primary key (id);
alter table edu.share_plan_courses add constraint pk_d5aukjiewdmk6smt3dwg7s8cq primary key (id);
alter table edu.share_plan_courses add constraint uk_4g3u5b9itdu90iij2y6la2ms5 unique (group_id,course_id);
alter table edu.share_plans add constraint pk_i76on9h6wjqohanirds5n3flp primary key (id);
alter table edu.std_alt_courses add constraint pk_fwqlciau51sypm3cjvy7rsqgp primary key (id);
alter table edu.std_alt_courses_news add constraint pk_ff9ka4gw208d53tn5bmg8v3yo primary key (std_alt_course_id,course_id);
alter table edu.std_alt_courses_olds add constraint pk_9lvrx45u53eynsj63a4c345rl primary key (std_alt_course_id,course_id);
alter table edu.std_book_orders add constraint pk_8233g912nk0k7gyf7ubaa3yf6 primary key (id);
alter table edu.std_course_abilities add constraint pk_ctriq5lvqq54p8st9q7qkkg20 primary key (id);
alter table edu.std_credit_stats add constraint pk_ifimhatpwc1ygx0mmukl2qkjn primary key (id);
alter table edu.std_exempt_courses add constraint pk_pmf5t4ig9yr2d7l6cha1r2b53 primary key (id);
alter table edu.std_gpas add constraint pk_d8hmmf1mnbxhuj1fi91q1n9rj primary key (id);
alter table edu.std_gpas add constraint uk_1pgtli4u8gcx191biigqq6mty unique (std_id);
alter table edu.std_leave_files add constraint pk_dr8s0l3a2j9jhm17kyp5no1n1 primary key (id);
alter table edu.std_leave_lessons add constraint pk_fvos8v6qystkps2poftah2g92 primary key (id);
alter table edu.std_leaves add constraint pk_p86cd7vat9xe52mnr96qe894p primary key (id);
alter table edu.std_program_bindings add constraint pk_9n0qo30hsm8dlofhfqppv2o94 primary key (id);
alter table edu.std_program_bindings add constraint uk_c966tfqv5ixyy0sxufc8w6osc unique (std_id);
alter table edu.std_semester_gpas add constraint pk_fqb6mob02oox7m3qiy43y5g3f primary key (id);
alter table edu.std_semester_gpas add constraint uk_54djya8v8f1shu5uutr9e555e unique (std_gpa_id,semester_id);
alter table edu.std_year_gpas add constraint pk_3ad0t5p7c2vmp6ktrbtgiwbwb primary key (id);
alter table edu.std_year_gpas add constraint uk_e0src4xf9uskqtilum6e01344 unique (std_gpa_id,school_year);
alter table edu.subclazzes add constraint pk_r86ec4dvfg6l28xam7g5sunpt primary key (id);
alter table edu.syllabus_assessments add constraint pk_kkqki8ddvk7onx4uuooy2utc6 primary key (id);
alter table edu.syllabus_cases add constraint pk_c6rj8fnvnwtvocppfplamaej primary key (id);
alter table edu.syllabus_docs add constraint pk_a2faop911g1x1pkx4mtf3mool primary key (id);
alter table edu.syllabus_experiments add constraint pk_baulexp8qydt31g95omfugrnb primary key (id);
alter table edu.syllabus_hours add constraint pk_esenbqqojcpudxho42gvtfpne primary key (id);
alter table edu.syllabus_method_designs add constraint pk_8t8k3wtg8lwwd8useqr6t9r7 primary key (id);
alter table edu.syllabus_objectives add constraint pk_nqtxa7ru8pkinx8a58ed3mwac primary key (id);
alter table edu.syllabus_objectives add constraint uk_qcf83a87e0bfew53ny7n8wyrt unique (syllabus_id,code);
alter table edu.syllabus_outcomes add constraint pk_fkpwvl02mv1b3t242nvjdhc7y primary key (id);
alter table edu.syllabus_texts add constraint pk_2rachttiq9lrns6e7hg27u4qi primary key (id);
alter table edu.syllabus_topic_elements add constraint pk_96jmnw2djmc7krs2lmajwimmu primary key (id);
alter table edu.syllabus_topic_hours add constraint pk_gvfpeyn4hpqvnncfuqj8uymtt primary key (id);
alter table edu.syllabus_topic_hours add constraint uk_gnlcnb1b2bc4egpay5tjm8qyo unique (topic_id,nature_id);
alter table edu.syllabus_topics add constraint pk_gw33mmc7iikocb980jda9ma31 primary key (id);
alter table edu.syllabuses add constraint pk_djhmwl2mslpebwr381gmwjina primary key (id);
alter table edu.syllabuses add constraint uk_53qtlhikj7jd9epqcxw2cqlm unique (semester_id,course_id,writer_id,doc_locale);
alter table edu.syllabuses_levels add constraint pk_n185xcaot9m60564kxp5ohyn1 primary key (syllabus_id,education_level_id);
alter table edu.syllabuses_majors add constraint pk_4qqybaphvt9hw8atbls2c0271 primary key (syllabus_id,major_id);
alter table edu.syllabuses_textbooks add constraint pk_roavbd30hbhgqvt2w6uw5if7 primary key (syllabus_id,textbook_id);
alter table edu.teaching_loads add constraint pk_s4s5ejob4j5b5skxdivgcndvk primary key (id);
alter table edu.term_campuses add constraint pk_e8xtqcnfg6h5q2vv9bicgyyo1 primary key (id);
alter table flow.edu_cert_exempt_applies add constraint pk_j9mm2s1kypj1542qj1y5nrhi1 primary key (id);
alter table flow.edu_cert_exempt_applies_courses add constraint pk_m5mfjxqjwukvr0bgbo5tdgckh primary key (cert_exempt_apply_id,course_id);
alter table flow.edu_course_alt_applies add constraint pk_popddywilpyvshedkxhr63fdf primary key (id);
alter table flow.edu_course_alt_applies_news add constraint pk_gqnomm9viapyih10a80bbtnlb primary key (course_alt_apply_id,course_id);
alter table flow.edu_course_alt_applies_olds add constraint pk_g6txw6v9s6cf0y2j61x1yrlor primary key (course_alt_apply_id,course_id);
alter table flow.edu_course_type_change_applies add constraint pk_g2hslvtwrshn2nlcw99p8u8vs primary key (id);
alter table flow.edu_exam_defer_applies add constraint pk_i1iyaj8qq0fuklt6jwr4ul46w primary key (id);
alter table flow.edu_exam_defer_applies add constraint uk_ofugueg4ao1omnyjbekru7j37 unique (std_id,clazz_id,exam_type_id);
alter table flow.edu_extern_exempt_applies add constraint pk_myj9vd8b658rfxdkn7gjontk1 primary key (id);
alter table flow.edu_extern_exempt_applies add constraint uk_ewl3g4qnuueaav63fnu8x9mtn unique (extern_student_id);
alter table flow.edu_new_course_applies add constraint pk_c2hfstwqwcmyo86xfc4v4llu3 primary key (id);
alter table flow.edu_new_course_applies_tags add constraint pk_6n9cq37up5f509auhglv3lqqk primary key (new_course_apply_id,course_tag_id);
alter table flow.edu_new_course_apply_hours add constraint pk_9o8bhp7vs4pxwkcyeluduysai primary key (id);
alter table flow.edu_new_course_categories add constraint pk_ooyymrpkh76y78k7y935mt7l4 primary key (id);
alter table flow.edu_new_course_categories add constraint uk_9uibg29bcb9318kfgrx82ce0l unique (code);
alter table flow.edu_new_course_departs add constraint pk_jbaiwlql5545t7atoyyltjl6p primary key (id);
alter table flow.flow_types add constraint pk_ehgs3p5kwrerow9mydbi4j3tc primary key (id);
alter table flow.process_logs add constraint pk_pg4kxtmg5fqls4l221xt6b9cn primary key (id);
alter table his.edu_course_grades add constraint pk_chti3605ct02gr38n41fa3w2r primary key (id,school_year);
alter table his.edu_course_profiles add constraint pk_bp6we1odwfrduqd0w2dbcmm5x primary key (id);
alter table his.edu_course_takers add constraint pk_ft65qhx6or053wtcbkflg9kuw primary key (id,school_year);
alter table his.edu_exam_grades add constraint pk_51dkrdiskm07r9s0g0r5mv1ei primary key (id,school_year);
alter table his.edu_exam_takers add constraint pk_s7u6opjyel7xwlqxxavdnikq3 primary key (id,school_year);
alter table his.edu_ga_grades add constraint pk_jmcwmshd9usxt264y2pyj8wt4 primary key (id,school_year);
alter table his.edu_regular_grades add constraint pk_lliu205c73xio4nmhoawmok7t primary key (id,school_year);
alter table lab.lab_experiments add constraint pk_cluasve2mn5lsm6jvfxqs77v8 primary key (id);
alter table lab.lab_experiments add constraint uk_eopmlqm6bmh71p4qw6wdxrfoo unique (task_id,idx);
alter table lab.lab_tasks add constraint pk_pobmn5lqgf0ngijre9cvc3id9 primary key (id);
alter table lab.lab_tasks_labs add constraint pk_m055on3ewsrwn869g19w0fixo primary key (lab_task_id,laboratory_id);
alter table log.edu_grade_changes add constraint pk_avwxfilyf3q6wgc4oepc6up77 primary key (id);
alter table log.edu_room_apply_audit_logs add constraint pk_ocfq5rdpfs7hbgaukwe3r0a3x primary key (id);
alter table log.std_spa_downloads add constraint pk_lvpw649482hrcwssqe7126o0x primary key (id);
alter table log.std_spa_prints add constraint pk_6x1bwsiwfd5jdcats3mnjovex primary key (id);
alter table log.std_transfer_apply_logs add constraint pk_je8lknq8ke5qe3u8vjyxrbqlo primary key (id);
alter table prac.ability_credit_applies add constraint pk_jrx2ap3o6wenlo8879ife098j primary key (id);
alter table prac.ability_credits add constraint pk_94rnfwyukm6a9ch8lh4b24jtu primary key (id);
alter table prac.ability_credits add constraint uk_oe22t4o0pgpw8ig651ulvxs2v unique (std_id);
alter table prac.inv_batches add constraint pk_26eu4n6mvkkawtd9p8nyc58wb primary key (id);
alter table prac.inv_closure_review_details add constraint pk_1b4ggxr300ebb51fc212hx4r primary key (id);
alter table prac.inv_closure_review_groups add constraint pk_6c4rjcbht2592mtspwayi9kar primary key (id);
alter table prac.inv_closure_review_groups_experts add constraint pk_8ul02gtuobjohhs8hbfqh5b2i primary key (closure_review_group_id,expert_id);
alter table prac.inv_closure_reviews add constraint pk_c86a40ptsd4av8ra1ctcutent primary key (id);
alter table prac.inv_closures add constraint pk_22ch6g6tq6697mf0d2l4ip6vn primary key (id);
alter table prac.inv_experts add constraint pk_2g4o8wotk79thelc7ggmeyfgf primary key (id);
alter table prac.inv_init_review_details add constraint pk_djyah74eyn02aqlimc34rongv primary key (id);
alter table prac.inv_init_review_groups add constraint pk_kwq4d0u1l01n5ckhm2acefd1l primary key (id);
alter table prac.inv_init_review_groups_experts add constraint pk_i3cm734r0fyam45ukbs5kdscb primary key (init_review_group_id,expert_id);
alter table prac.inv_init_reviews add constraint pk_k50vknsvhw3h9xacr5qryrub7 primary key (id);
alter table prac.inv_introes add constraint pk_7uyfsg7aoqw6b5em74nj1ycqe primary key (id);
alter table prac.inv_level_jounals add constraint pk_p32r7mb8i2943uveupn0n815a primary key (id);
alter table prac.inv_materials add constraint pk_3ouunikiphs7y50md8yv0at1y primary key (id);
alter table prac.inv_members add constraint pk_de3fosi9vb65pxv8s5f849fxs primary key (id);
alter table prac.inv_members add constraint uk_nqejhpjmj9jdt59pxnaxsyf8a unique (project_id,std_id);
alter table prac.inv_project_categories add constraint pk_mx8lpbqvtwtv3npu3t3dntbl4 primary key (id);
alter table prac.inv_project_levels add constraint pk_742eum08363tyw0rae780jcuo primary key (id);
alter table prac.inv_project_states add constraint pk_a9a7lsr3hvbjd33wxdtwakhjy primary key (id);
alter table prac.inv_projects add constraint pk_6rijukmxxnvtd3a5b1xbc92rm primary key (id);
alter table prac.inv_projects_instructors add constraint pk_jsow4fy8ru7u15bh43on17jx2 primary key (project_id,teacher_id,idx);
alter table prac.inv_promotion_defense_groups add constraint pk_34o2p0mvvg6mfy9tv5mm8hupe primary key (id);
alter table prac.inv_promotion_defense_members add constraint pk_b4nhltmsnowel3c1ogfvdnt7d primary key (id);
alter table prac.inv_promotion_defense_members add constraint uk_gouy23rxmvq3qpcbyfdphdthj unique (group_id,idx);
alter table prac.inv_stage_types add constraint pk_rxwn79ifobeyupjueaxnwqksi primary key (id);
alter table prac.inv_stages add constraint pk_mnxxfplf9544qamdh72e4gody primary key (id);
alter table prac.prac_activities add constraint pk_jclfmqktn7gbydoinimflkuge primary key (id);
alter table prac.prac_activities_teachers add constraint pk_m6rcxc6wq5ladivqpne64hrg9 primary key (prac_activity_id,user_id);
alter table prac.prac_activity_schedules add constraint pk_en5y6abajte148s2vp97tbye7 primary key (id);
alter table prac.prac_activity_schedules_teachers add constraint pk_6sbuukfwaggk7mw12rhcvkh3m primary key (prac_activity_schedule_id,user_id);
alter table prac.prac_clazz_schedules add constraint pk_ths47bln2u831lk23ws7lqux3 primary key (id);
alter table prac.prac_clazz_schedules_teachers add constraint pk_4efp5dstwyj6rb2a05gtg6211 primary key (prac_clazz_schedule_id,user_id);
alter table prac.prac_clazzes add constraint pk_ahrdt1c1amwedh0v6cw76rkko primary key (id);
alter table prac.prac_clazzes_teachers add constraint pk_ktwf35buybr0fj5k0f47lvcoo primary key (prac_clazz_id,user_id);
alter table prac.std_practice_hours add constraint pk_re8dtd5sef7xvesjfjhfgayhw primary key (id);
alter table prac.std_practice_hours add constraint uk_iy7h2lrkq2jd9misuc1ovhmir unique (std_id,category_id);
alter table prac.std_practice_infoes add constraint pk_18vfbtkmyahbpya2j6hc90go5 primary key (id);
alter table qos.assess_criterias add constraint pk_mbg8mfxchlyxb3rbpr5wophpe primary key (id);
alter table qos.assess_grades add constraint pk_cwbj8vblm76ow6w1i093jmtli primary key (id);
alter table qos.category_eval_stats add constraint pk_bq3ia61jmui8sv480n1sxf9ao primary key (id);
alter table qos.category_stat_grades add constraint pk_pmn7bnvtdgb2b8csk8dhtwtsi primary key (id);
alter table qos.category_stat_ranges add constraint pk_cv2ip2dgyo0tdy2p0ung5jpi5 primary key (id);
alter table qos.course_eval_stats add constraint pk_29v0q7x5wi3rvbtua754ljbo primary key (id);
alter table qos.course_indicator_stats add constraint pk_7jjkpgkgirlgdymq0juu64gy7 primary key (id);
alter table qos.course_option_stats add constraint pk_otrkkbyi100meit14vwi9ecqt primary key (id);
alter table qos.course_question_stats add constraint pk_rmgevn8gy92r0w10mmk5s7xyj primary key (id);
alter table qos.depart_eval_stats add constraint pk_p87qmm6ecwo7f9x37labrlk4y primary key (id);
alter table qos.evaluate_results add constraint pk_sjln57t9wh1oadhcwy8aiagck primary key (id);
alter table qos.feedbacks add constraint pk_3w69do02finwr5csfag3hr00u primary key (id);
alter table qos.final_comments add constraint pk_hh645iewh252rbq6jbpvlpuj1 primary key (id);
alter table qos.final_teacher_scores add constraint pk_9cv4kydmlobvgybnqpyyw68a primary key (id);
alter table qos.indicators add constraint pk_sfq7ixip97pxv9a4ug1sgwd3k primary key (id);
alter table qos.option_groups add constraint pk_gvmhlgmsyrwjo92qnevi2x234 primary key (id);
alter table qos.options add constraint pk_h7d0xw570w8ojgjkwivq1cng6 primary key (id);
alter table qos.question_results add constraint pk_rcpahtmwk6gyixcqpqcvwdtku primary key (id);
alter table qos.questionnaire_clazzes add constraint pk_arlumvuig3w4s661mswyvlteg primary key (id);
alter table qos.questionnaires add constraint pk_fufcai5j6hvvlr0wc6fpb8d6o primary key (id);
alter table qos.questionnaires_questions add constraint pk_41ugco3nqnt9c9x9taga06agn primary key (questionnaire_id,question_id);
alter table qos.questions add constraint pk_8be2ix7e7pkg5mjne8qegaj76 primary key (id);
alter table qos.school_eval_stats add constraint pk_qtq0xmlybs0ch9pjdq4cbpom2 primary key (id);
alter table std.archive_docs add constraint pk_8m2rjy6rh2l0le6vij6nuin0e primary key (id);
alter table std.bachelor2nd_applies add constraint pk_jn9sk0bv4n0roh3prtjkt4h9i primary key (id);
alter table std.bills add constraint pk_l2ycbilgr05krq0lg8r6qxnsp primary key (id);
alter table std.contacts add constraint pk_7ko2w4r57qng8yfiyi7n9snh4 primary key (id);
alter table std.contacts add constraint uk_qopxi21m45bqtuemmwurk7dkl unique (std_id);
alter table std.debts add constraint pk_hv6munekg3kbg6qh7yodxld9l primary key (id);
alter table std.degree_applies add constraint pk_85xktk94x3o87fc7wwtbo07i5 primary key (id);
alter table std.degree_applies add constraint uk_7pjmosme1tvk266r1b5ca6kds unique (std_id);
alter table std.degree_results add constraint pk_juk8stxairvjh8aqqgmus1vx2 primary key (id);
alter table std.edu_work_records add constraint pk_ow2kjrrf2ckemfeaucvejvy7u primary key (id);
alter table std.examinees add constraint pk_1e8il6rh29256vdjtbwh1y0fe primary key (id);
alter table std.examinees add constraint uk_2bqu9xw63m537f7cby311u7vr unique (std_id);
alter table std.exchange_programs add constraint pk_md99sroe2nv8btxk3cr7tp2an primary key (id);
alter table std.exchange_programs_schools add constraint pk_da8usceea51yrhkys93r6wcgw primary key (exchange_program_id,extern_school_id);
alter table std.foreigners add constraint pk_tr2lwiprket01b5xwsnoci4qd primary key (id);
alter table std.freshmen add constraint pk_lyewxqqmbjf9rgu4w4se50ddk primary key (id);
alter table std.graduate_batches add constraint pk_kb2t7xdi7imcxukogahdjojtq primary key (id);
alter table std.graduate_results add constraint pk_pwaqdnrn36ry8ef21e1k1kmu5 primary key (id);
alter table std.graduate_results add constraint uk_6xobo8150fh0351vpgl7apacm unique (batch_id,std_id);
alter table std.graduations add constraint pk_fvuvju96x5h9aw82xbep1a63v primary key (id);
alter table std.graduations add constraint uk_l54olf776vfr1sk99qp9vbjfh unique (batch_id,std_id);
alter table std.homes add constraint pk_ry45w9bb9c30yransxedxfoop primary key (id);
alter table std.homes add constraint uk_t42cafsv2e1s4k9l1rxdixf2x unique (std_id);
alter table std.honor_awards add constraint pk_82a0vokwcnncj8l0yi0s57wvc primary key (id);
alter table std.honor_categories add constraint pk_a6ucjxdfau1g7x22o5n014q2u primary key (id);
alter table std.honor_levels add constraint pk_l53d6eu3akfl5s2gq3o74wqa9 primary key (id);
alter table std.honor_types add constraint pk_c1tngwju5h6efg1jlicg9tvtj primary key (id);
alter table std.major_students add constraint pk_ge7r9q9q5db7ne2cfjul9pnm5 primary key (id);
alter table std.major_students add constraint uk_sp5y2w7s2e9uwp4okyf64ag63 unique (std_id);
alter table std.minor_signup_options add constraint pk_bjytbcxuwc4h61ffiqgvo0ytq primary key (id);
alter table std.minor_signup_settings add constraint pk_lbdv0iilu1f78dkfta76ob83p primary key (id);
alter table std.minor_signup_std_majors add constraint pk_4mc1rl2t3d6ficldtdl901qou primary key (id);
alter table std.minor_signup_stds add constraint pk_531wskv253921k4m6949sn2ir primary key (id);
alter table std.minor_signup_stds add constraint uk_mcjo5arixiaveju23pqxqx6aa unique (setting_id,idcard);
alter table std.orders add constraint pk_26gf4ikas867gkkiyjur6i708 primary key (id);
alter table std.orders add constraint uk_5rbs2yuu4l5occesk8783g2sh unique (bill_id);
alter table std.orders add constraint uk_gt3o4a5bqj59e9y6wakgk926t unique (code);
alter table std.person_check_items add constraint pk_5l9cllp6owmy5ni6yldt59wxp primary key (id);
alter table std.person_checks add constraint pk_gu67dbl0npvd2vc7mfb8fe51l primary key (id);
alter table std.plan_result_checks add constraint pk_iqh5lytwg28f79dfp31to2sx8 primary key (id);
alter table std.plan_result_checks add constraint uk_s6njlmsdy80cd3jfn7mcakm3e unique (std_id);
alter table std.punishments add constraint pk_n9h4mdiiwcc2512hqfwdu3w3 primary key (id);
alter table std.registers add constraint pk_6x7adbm1t7y079qhsobs4n9il primary key (id);
alter table std.scholarship_awards add constraint pk_56u7g5vxife5b22kc1duq23ua primary key (id);
alter table std.scholarship_categories add constraint pk_mq52nlda4709qvl5frjenasyv primary key (id);
alter table std.scholarship_levels add constraint pk_e1wrr4oa17lgng47f5rp1r862 primary key (id);
alter table std.scholarship_types add constraint pk_61wg2qxbi9mvbo8u75rkflwrx primary key (id);
alter table std.social_relations add constraint pk_kqm1n06eaj1ydahbybcgtgqn2 primary key (id);
alter table std.spa_print_quotas add constraint pk_tcgrsp5n95jn2la6yqef3cw5g primary key (id);
alter table std.std_alter_applies add constraint pk_pl84xb1wr2s9338d4f4kk7o92 primary key (id);
alter table std.std_alter_apply_steps add constraint pk_guolqow8ldtemrqwb2v6rxeyh primary key (id);
alter table std.std_alteration_items add constraint pk_o3d8j0mujuxorms8a36jw7ic5 primary key (id);
alter table std.std_alterations add constraint pk_a1ti0uv32d4ggaivn3y58e9c primary key (id);
alter table std.stipend_awards add constraint pk_7j9vvyns0himgc9ubwkixdnqa primary key (id);
alter table std.stipend_categories add constraint pk_fcn9q6gllh4ox76aycyatqgy8 primary key (id);
alter table std.stipend_levels add constraint pk_s2ptwfu0qp30q386yx6iedxsl primary key (id);
alter table std.subsidy_awards add constraint pk_2i78s7uvy951i87lqysmnm8a3 primary key (id);
alter table std.subsidy_categories add constraint pk_rrvx3ixuv9tqwxova51722juy primary key (id);
alter table std.subsidy_levels add constraint pk_h223qwt0qq24unbms55y0q5bp primary key (id);
alter table std.transfer_applies add constraint pk_1636v9ke8tssygsebwc8he7ex primary key (id);
alter table trd.rd_achievement_awards add constraint pk_jrurc91k5s98dupbvbiucs605 primary key (id);
alter table trd.rd_achievement_members add constraint pk_13aseiekqtn3gmtqw4u0ortdo primary key (id);
alter table trd.rd_achievement_types add constraint pk_ta42fnnl0b3oljvweg6mflnwd primary key (id);
alter table trd.rd_achievement_types add constraint uk_sg5cv23t8wxl2pdm7hs44oovv unique (code);
alter table trd.rd_achievements add constraint pk_kcqw8m7fdba9xh17q6sm4kxtd primary key (id);
alter table trd.rd_project_categories add constraint pk_8ad75c7otnko05ptv7cs56eos primary key (id);
alter table trd.rd_project_categories add constraint uk_lm068o3s4253ai1s8dkm17r77 unique (code);
alter table trd.rd_project_members add constraint pk_fx6ud9yt7chj5wgi8jsjxe1vd primary key (id);
alter table trd.rd_project_statuses add constraint pk_2l8sy0rmcghk1vv78aur11wmw primary key (id);
alter table trd.rd_project_statuses add constraint uk_64ybhe0mvvwxkaw2woo44aycp unique (code);
alter table trd.rd_projects add constraint pk_sn8pn1wp0f8awmjy42hcmnmoc primary key (id);
alter table trd.rd_projects_leaders add constraint pk_te6ajmxgr9o0402uvfenplpvh primary key (rd_project_id,user_id);
alter table trd.teaching_team_members add constraint pk_b0hsatym04m5isj6oxjjmmfbb primary key (id);
alter table trd.teaching_teams add constraint pk_k1qfb3g4prtlvhoqsw3cq0ska primary key (id);
alter table trd.teaching_teams_leaders add constraint pk_aqg74musb0j1qtonp6uy9vupg primary key (teaching_team_id,user_id);
alter table trd.textbook_achievements add constraint pk_301jawapmi8866dn1wo04dr62 primary key (id);
alter table trd.textbook_awards add constraint pk_mf7o4jj1qfw8k0d3akw2g95s7 primary key (id);
alter table trd.textbook_editors add constraint pk_6l1cf8pefv3kvorgvxyk7qrm8 primary key (id);
