alter table base.buildings add constraint pk_isptetvkhnkbsd7qqyed4vjy6 primary key (id);
alter table base.buildings add constraint uk_57bnctn8fdawxdyp9lpaxbgjt unique (school_id,code);
alter table base.c_book_award_types add constraint c_book_award_types_code_key unique (code);
alter table base.c_book_award_types add constraint pk_h2auvi381y09pj3yogmu0dkcn primary key (id);
alter table base.c_book_types add constraint c_book_types_code_key unique (code);
alter table base.c_book_types add constraint pk_d8duuj55oxjq3a2diipdedlck primary key (id);
alter table base.c_course_ability_rates add constraint c_course_ability_rates_code_key unique (code);
alter table base.c_course_ability_rates add constraint pk_bgsi7jt2ydrd4g7un61vyk0wq primary key (id);
alter table base.c_course_categories add constraint c_course_categories_code_key unique (code);
alter table base.c_course_categories add constraint pk_4a82ko2a6rqjpct6lyocxtfw0 primary key (id);
alter table base.c_course_types add constraint c_course_types_code_key unique (code);
alter table base.c_course_types add constraint pk_ad7srp158yyt3qqfnho3du3b2 primary key (id);
alter table base.c_education_types add constraint c_education_types_code_key unique (code);
alter table base.c_education_types add constraint pk_ct9svvtbjc2g6i7erusn11hgs primary key (id);
alter table base.c_fee_types add constraint c_fee_types_code_key unique (code);
alter table base.c_fee_types add constraint pk_arhwas5ou48lb9euph8py4f1b primary key (id);
alter table base.c_std_label_types add constraint c_std_label_types_code_key unique (code);
alter table base.c_std_label_types add constraint pk_jsvqoo99gu44bmdynjo11lw7i primary key (id);
alter table base.c_std_labels add constraint c_std_labels_code_key unique (code);
alter table base.c_std_labels add constraint pk_eenp8ej7lgwccvfl9gely2b2d primary key (id);
alter table base.c_std_types add constraint c_std_types_code_key unique (code);
alter table base.c_std_types add constraint pk_madxfpue18kxxvmx2an9k8fxb primary key (id);
alter table base.calendar_stages add constraint pk_bwq0g3d1exgmi6u4ss0me8y3m primary key (id);
alter table base.calendars add constraint pk_b2bvaskon8lysbk1srdwtml4f primary key (id);
alter table base.calendars add constraint uk_9k89gny3vqpqyk7mkhuxg16fi unique (school_id,code);
alter table base.campuses add constraint pk_7b3jpnegqwbvpg4marvqwpn46 primary key (id);
alter table base.campuses add constraint uk_iyq5494wgreojxq596lo7iijs unique (school_id,code);
alter table base.classrooms add constraint pk_d7h30ub9pduroys2e5318ti55 primary key (id);
alter table base.classrooms add constraint uk_3rf701tm9q4qyua4q0ydybv95 unique (code);
alter table base.classrooms_departs add constraint pk_n5duwpuh4oq58kk8i61odk7h7 primary key (classroom_id,department_id);
alter table base.classrooms_projects add constraint pk_cjgojafxa077u3fb2vicargx primary key (classroom_id,project_id);
alter table base.course_clusters add constraint pk_6gjj4kp1e06ob51efr5det0ot primary key (id);
alter table base.course_clusters add constraint uk_jvovhm8hp7ph6s50s7fvq90wt unique (project_id,code);
alter table base.course_hours add constraint pk_euy5bifeg4jalgolkkxa21w3f primary key (id);
alter table base.course_hours add constraint uk_pr9ombr8rdoadj4w1xbu80gk7 unique (course_id,teaching_nature_id);
alter table base.course_levels add constraint pk_1mqdklheeg8p8nx65q4l3og8g primary key (id);
alter table base.course_levels add constraint uk_59cbmhw5789an69kcq0j5g9i8 unique (course_id,level_id);
alter table base.course_profiles add constraint pk_faiglxbssjx4v3eskg2fjq6uy primary key (id);
alter table base.course_profiles add constraint uk_tjt1ybpj33nkgqek0j2fylp7g unique (course_id);
alter table base.course_units add constraint pk_9eybgcnr9huwt9f43c30xud1m primary key (id);
alter table base.courses add constraint pk_1lyj037fss3plmcutpx9b4r2x primary key (id);
alter table base.courses add constraint uk_thp7tiw1cr1mvm9uy21fqflch unique (project_id,code);
alter table base.courses_ability_rates add constraint pk_o072av0vclfvq7gpvr9gxat6u primary key (course_id,course_ability_rate_id);
alter table base.courses_grading_modes add constraint pk_pmy94fkg457bni4cgs3nfsbyp primary key (course_id,grading_mode_id);
alter table base.courses_majors add constraint pk_eymkpxyqwpqqtaond0nj71g1s primary key (course_id,major_id);
alter table base.courses_prerequisites add constraint pk_oshk6vwdtq9ycqsmj1jh6nxki primary key (course_id,prerequisite_id);
alter table base.courses_teachers add constraint pk_lj3gh310g6ro1s6t13qunca7a primary key (course_id,teacher_id);
alter table base.courses_textbooks add constraint pk_su8h61lhgrbuv4l18nkjb874 primary key (course_id,textbook_id);
alter table base.courses_xmajors add constraint pk_2g7t6j5hy2w3bltscs5tq09d4 primary key (course_id,major_id);
alter table base.dayoffs add constraint pk_7180815am4o2cdnqinp2upxi1 primary key (id);
alter table base.departments add constraint pk_njmudssqklm265fj3qxrl6v4i primary key (id);
alter table base.departments add constraint uk_blem78dvbmeuekoy0jg6px6j7 unique (school_id,code);
alter table base.departments_campuses add constraint pk_hayeukvl4wxa5t4wj8u012cvy primary key (department_id,campus_id);
alter table base.direction_journals add constraint pk_rvbr7ldfxrsat8i1nhedoinwk primary key (id);
alter table base.directions add constraint pk_j2qwo6upqlwqexl7chxnno9mw primary key (id);
alter table base.directions add constraint uk_ry4fda3w2fdnnsfl7yrnpha1 unique (project_id,code);
alter table base.extern_schools add constraint pk_nj2mnlh45jh2wagd9heuq58dl primary key (id);
alter table base.extern_students add constraint pk_8omlfu3itguya4lmcd6pxe0wd primary key (id);
alter table base.grades add constraint pk_tfax6erblyil71kws4l93yhnv primary key (id);
alter table base.grades add constraint uk_enpnepu169ecfvnnni3oayeva unique (project_id,code);
alter table base.graduate_seasons add constraint pk_ajyxkx6bgsd5hh3tst2x0qrs0 primary key (id);
alter table base.graduate_seasons add constraint uk_q1npfkscf2dd26j0ie8sdlvl unique (project_id,code);
alter table base.graduates add constraint pk_861dttwawbactk5wx2pb5sfg1 primary key (id);
alter table base.graduates add constraint uk_fjm29o037eumvq25eojdp797r unique (std_id);
alter table base.holidays add constraint pk_o7r9qruakt8wxjndgnml60u7r primary key (id);
alter table base.major_disciplines add constraint pk_oifn3upq6ylafj81hb805ut1l primary key (id);
alter table base.major_journals add constraint pk_7gepwk5lg9b0ixt7ww2tum8gm primary key (id);
alter table base.majors add constraint pk_p9yolyf8gx5n3i5kh4utj6klv primary key (id);
alter table base.majors add constraint uk_8vnop0jo5r3n5lvausdjy13aj unique (project_id,code);
alter table base.mentors add constraint pk_b2barjxncjg1kb2ilm8dw1r3s primary key (id);
alter table base.mentors add constraint uk_4n9545nrhwav5b96nw9k2di1t unique (staff_id);
alter table base.mentors_projects add constraint pk_p14hk70e30r9eyqy9ol7jn5xm primary key (mentor_id,project_id);
alter table base.minor_majors add constraint pk_puyx3wltdpl9vv77rj77l9txc primary key (id);
alter table base.people add constraint pk_25uwl12dj9en3iflug9w23r1q primary key (id);
alter table base.project_codes add constraint pk_h8pb4rkgymaq67flwfvm8mdvg primary key (id);
alter table base.project_properties add constraint pk_rfrpbcb39anra9nb0a5x1g6dd primary key (id);
alter table base.project_properties add constraint uk_1kgy8wfyw9wg1e28k8seg64se unique (project_id,name);
alter table base.projects add constraint pk_68i13lhb2otxe0ptivfl1qpeh primary key (id);
alter table base.projects add constraint projects_code_key unique (code);
alter table base.projects_campuses add constraint pk_cxhgbnp68mvn8mhg6wpa8po7j primary key (project_id,campus_id);
alter table base.projects_departments add constraint pk_c3pws6toenjk026awpmfjnul6 primary key (project_id,department_id);
alter table base.projects_edu_types add constraint pk_dbq66x3eva45j6uofa2qrre3n primary key (project_id,education_type_id);
alter table base.projects_levels add constraint pk_f8wpx8th02k4kus25oq36p79n primary key (project_id,education_level_id);
alter table base.projects_std_labels add constraint pk_gpnc9xr0cnwkqao6sq7arohpc primary key (project_id,std_label_id);
alter table base.projects_std_types add constraint pk_8rp3u9k569jpshgo6y2unauns primary key (project_id,std_type_id);
alter table base.rooms add constraint pk_nsj160cru1j6fbgp9le397om7 primary key (id);
alter table base.rooms add constraint uk_b5l9ebt0gr0vn3qv9qtl0ii71 unique (school_id,code);
alter table base.school_lengths add constraint pk_dy2p1op9w9eh33o0jks159fxe primary key (id);
alter table base.schools add constraint pk_rb90lq0thr3gqpksvhme60v6r primary key (id);
alter table base.schools add constraint schools_code_key unique (code);
alter table base.semester_stages add constraint pk_g7yquh6x73a5obad6ie8qwso8 primary key (id);
alter table base.semesters add constraint pk_7x6cesd88ki649j15p748hfl0 primary key (id);
alter table base.semesters add constraint uk_kd2xc25i3147f18f3i02rkisg unique (calendar_id,code);
alter table base.squads add constraint pk_flc1bpx9eojc9pwda23uoujej primary key (id);
alter table base.squads add constraint uk_6pm1jee6jdt4ynlnllhpj59f2 unique (project_id,code);
alter table base.staff_profiles add constraint pk_qhyynhx18vx1bi91rhlxlunkb primary key (id);
alter table base.staff_profiles add constraint uk_ocmcnctnhlbe30lj7wwi7c4ks unique (staff_id);
alter table base.staff_titles add constraint pk_c3kp7wxy16bvr5wxt7qo0nk2d primary key (id);
alter table base.staffs add constraint pk_qi7hj56hag2uu4e5eu4egoxrl primary key (id);
alter table base.staffs add constraint uk_ksaq070k32jb6aey065dd9xv0 unique (school_id,code);
alter table base.student_states add constraint pk_4qvivd9quhlhb7ft0dsewhsnt primary key (id);
alter table base.students add constraint pk_dp1c3lp7694lu2ri6rfh6n7g8 primary key (id);
alter table base.students add constraint uk_50fnp38f8oyhuolhke7nu920t unique (code,project_id);
alter table base.students_labels add constraint pk_ramuktutb3f32cwgsbe0apovk primary key (student_id,std_label_id,std_label_type_id);
alter table base.teachers add constraint pk_k6sh5di4vpqtsxxvusqlb0vg5 primary key (id);
alter table base.teachers add constraint uk_cd1k6xwg9jqtiwx9ybnxpmoh9 unique (user_id);
alter table base.teachers add constraint uk_hwllts0elb03lqv7yenjhk3dt unique (staff_id);
alter table base.teachers_campuses add constraint pk_4wtyv7xyavsa0tlo5g8rl0txy primary key (teacher_id,campus_id);
alter table base.teachers_projects add constraint pk_ksmq83maw97gk85mth4s2g99n primary key (teacher_id,project_id);
alter table base.teaching_offices add constraint pk_cqhu9i1m9mg4ekr9tuv58c744 primary key (id);
alter table base.teaching_offices add constraint uk_90yrmn6u3xmkpyo348xl31ihq unique (project_id,code);
alter table base.textbooks add constraint pk_8fiuofquw103fs3v8kkco0orm primary key (id);
alter table base.time_settings add constraint pk_c883txidvf5q332sj20l5n5fx primary key (id);
alter table base.users add constraint pk_i4mlr3lp5ixml05sx2wuk8kp8 primary key (id);
alter table base.users add constraint uk_rtwk6iqyuv8d7se1gkkumd948 unique (school_id,code);
alter table base.versions add constraint pk_kn37tnh6h9broruk4q2gsyyip primary key (id);
alter table cfg.edu_capacity_factors add constraint pk_svrnfofl3ds355csgefiyf0s8 primary key (id);
alter table cfg.edu_cert_exempt_configs add constraint pk_25ogrkq3scobs3rr6jvtx7j01 primary key (id);
alter table cfg.edu_cert_exempt_courses add constraint pk_8vtdq21yu199uqukr5u4qgr2n primary key (cert_exempt_setting_id,course_id);
alter table cfg.edu_cert_exempt_settings add constraint pk_bvnsnltdgqpnel6hg2wa8bl6s primary key (id);
alter table cfg.edu_cert_signup_configs add constraint pk_ifi79764glfik2b7auy55mucv primary key (id);
alter table cfg.edu_cert_signup_exclusives add constraint pk_t5s02uj9t8c9q7kxg7itbqam5 primary key (cert_signup_setting_id,certificate_subject_id);
alter table cfg.edu_cert_signup_scopes add constraint pk_78sh49aebqqecr73d449nj7fa primary key (id);
alter table cfg.edu_cert_signup_settings add constraint pk_cakh1me82ck12w2beinktj169 primary key (id);
alter table cfg.edu_exam_alloc_settings add constraint pk_jx9fvbxw2mt1y3pcb1axj0wh8 primary key (id);
alter table cfg.edu_factor_segments add constraint pk_6jhqow1nyqkq8bomfi4pa4bs1 primary key (id);
alter table cfg.edu_grade_input_switches add constraint pk_sipio4c1axlo0u1aps51brdkx primary key (id);
alter table cfg.edu_grade_input_switches_types add constraint pk_ha7tebsm4ds67bcc3pd4vjuv2 primary key (grade_input_switch_id,grade_type_id);
alter table cfg.edu_grade_rate_configs add constraint pk_43r3gq2u9mxeo8vnat53p96kn primary key (id);
alter table cfg.edu_grade_rate_items add constraint pk_bl6jfoa15bivbeyy7bp965w81 primary key (id);
alter table cfg.edu_room_apply_depart_rooms add constraint pk_qipdsh9c69rotfatomryk6tpb primary key (room_apply_depart_scope_id,classroom_id);
alter table cfg.edu_room_apply_depart_scopes add constraint pk_h2vnbajvln52auo26uwsbd5s7 primary key (id);
alter table cfg.edu_room_apply_settings add constraint pk_iup28tmtsr5rdo12mqxwjetjj primary key (id);
alter table cfg.edu_schedule_setting_departs add constraint pk_1j3pnliwolxppebfq88n5r6i2 primary key (id);
alter table cfg.edu_schedule_settings add constraint pk_4m049ge32ldi4uglemj34w77d primary key (id);
alter table cfg.edu_transcript_templates add constraint pk_m87tyokii4burhxl6mcqok1a2 primary key (id);
alter table cfg.qos_feedback_switches add constraint pk_b7whkf51jgmhbp82phl3dt2hr primary key (id);
alter table cfg.qos_std_evaluate_switches add constraint pk_81sba75u2yf8yhm3tjcyrsns primary key (id);
alter table cfg.spa_coupons add constraint pk_rwsiaat8v0lgqu155yayo8bdy primary key (id);
alter table cfg.spa_doc_types add constraint pk_2w8y445q9wgvl9ddrtljltpwt primary key (id);
alter table cfg.spa_print_configs add constraint pk_3f8qp6ur569ahp33vlyhyo4mb primary key (id);
alter table cfg.std_register_sessions add constraint pk_ofhf9115x2ra5xlq0vxmx13t5 primary key (id);
alter table cfg.std_std_alter_configs add constraint pk_nyp7vi8oa6vdk3x8sx15fkdrs primary key (id);
alter table cfg.std_transfer_options add constraint pk_kjwut08vmlyklxegooc1nftgo primary key (id);
alter table cfg.std_transfer_schemes add constraint pk_3ccwikukhp020f3uwobm76b0b primary key (id);
alter table cfg.std_transfer_scopes add constraint pk_3kj34q98ib4bmssbl2n33jqww primary key (id);
alter table cfg.std_transfer_scopes_grades add constraint pk_8em7ugqxysbj9ftc3tn2wwfvn primary key (transfer_scope_id,value_);
alter table cfg.std_transfer_scopes_majors add constraint pk_ens0r0ptm7qgcdo1hkkkkoded primary key (transfer_scope_id,major_id);
alter table cfg.std_tuition_configs add constraint pk_1dxvmk5aqbmc4h23c2e25ed9o primary key (id);
alter table code.academic_levels add constraint academic_levels_code_key unique (code);
alter table code.academic_levels add constraint pk_q51xfy75i97otjcrinh3ioojl primary key (id);
alter table code.activity_types add constraint activity_types_code_key unique (code);
alter table code.activity_types add constraint pk_cmb1g96s43erp3tu63b3t5c3r primary key (id);
alter table code.admission_types add constraint admission_types_code_key unique (code);
alter table code.admission_types add constraint pk_a6q355jjrx7gsqp1gfus8kc09 primary key (id);
alter table code.blood_types add constraint blood_types_code_key unique (code);
alter table code.blood_types add constraint pk_s815d9t06dbnd8qc42j9cmbiy primary key (id);
alter table code.book_categories add constraint book_categories_code_key unique (code);
alter table code.book_categories add constraint pk_lkbpdt3molrx8lrsafy7ter00 primary key (id);
alter table code.building_types add constraint building_types_code_key unique (code);
alter table code.building_types add constraint pk_9fv09o2b3rsbo9ynt7ik8coj1 primary key (id);
alter table code.classroom_types add constraint classroom_types_code_key unique (code);
alter table code.classroom_types add constraint pk_jqhkc4fgq6xtd8q45034q62h9 primary key (id);
alter table code.compatriot_types add constraint compatriot_types_code_key unique (code);
alter table code.compatriot_types add constraint pk_72f3nrjp1nlnvxqku2roeb22x primary key (id);
alter table code.countries add constraint countries_code_key unique (code);
alter table code.countries add constraint pk_d8ehdli05dbs8aiu5yxq6ek0a primary key (id);
alter table code.course_natures add constraint course_natures_code_key unique (code);
alter table code.course_natures add constraint pk_qmyas7mib2hjnqnj6ogbi2n7p primary key (id);
alter table code.course_take_types add constraint course_take_types_code_key unique (code);
alter table code.course_take_types add constraint pk_qkahh6b0jdyhg34u94jvoqseo primary key (id);
alter table code.day_parts add constraint day_parts_code_key unique (code);
alter table code.day_parts add constraint pk_smmdo7fq2ewnj1lx98wxxdq91 primary key (id);
alter table code.degree_levels add constraint degree_levels_code_key unique (code);
alter table code.degree_levels add constraint pk_fiqbw5nsr2mw36xoxhj1j2116 primary key (id);
alter table code.degrees add constraint degrees_code_key unique (code);
alter table code.degrees add constraint pk_2v97ef4fui6mhritxr8eaanvd primary key (id);
alter table code.department_categories add constraint department_categories_code_key unique (code);
alter table code.department_categories add constraint pk_mf4to82tja75w579ae7netvca primary key (id);
alter table code.difficulty_causes add constraint difficulty_causes_code_key unique (code);
alter table code.difficulty_causes add constraint pk_lq6iocryw9m7olt9euio0caju primary key (id);
alter table code.difficulty_degrees add constraint difficulty_degrees_code_key unique (code);
alter table code.difficulty_degrees add constraint pk_a4fi6imv2vy8ddql3he4ayuc primary key (id);
alter table code.discipline_catalogs add constraint discipline_catalogs_code_key unique (code);
alter table code.discipline_catalogs add constraint pk_ldh031tie4eg35sgutxwnqorn primary key (id);
alter table code.discipline_categories add constraint discipline_categories_code_key unique (code);
alter table code.discipline_categories add constraint pk_rnaagxursry83nehmsmy5wj87 primary key (id);
alter table code.disciplines add constraint disciplines_code_key unique (code);
alter table code.disciplines add constraint pk_dxv54dx9an08euovln6cd5s4x primary key (id);
alter table code.divisions add constraint divisions_code_key unique (code);
alter table code.divisions add constraint pk_ckagbn1mtjluopfx7m4ddosoi primary key (id);
alter table code.duty_grades add constraint duty_grades_code_key unique (code);
alter table code.duty_grades add constraint pk_sl8vmsl3f1jfpwosg32bccq9u primary key (id);
alter table code.duty_types add constraint duty_types_code_key unique (code);
alter table code.duty_types add constraint pk_rlhgyb1b3q18kigee1df4kde6 primary key (id);
alter table code.edu_categories add constraint edu_categories_code_key unique (code);
alter table code.edu_categories add constraint pk_7p50hi0fsqia82miiqrf6ldas primary key (id);
alter table code.education_degrees add constraint education_degrees_code_key unique (code);
alter table code.education_degrees add constraint pk_k83kie42e7dp161rew35xyojq primary key (id);
alter table code.education_levels add constraint education_levels_code_key unique (code);
alter table code.education_levels add constraint pk_nqts5vnrhlor1x9p5xk5p8dsv primary key (id);
alter table code.education_modes add constraint education_modes_code_key unique (code);
alter table code.education_modes add constraint pk_riccou6iptrw79s4j9rh1r2ne primary key (id);
alter table code.education_results add constraint education_results_code_key unique (code);
alter table code.education_results add constraint pk_r5o2htr643q9k2keiote10x13 primary key (id);
alter table code.election_modes add constraint election_modes_code_key unique (code);
alter table code.election_modes add constraint pk_fe9eki74ur0gxgx89lk8y8vsc primary key (id);
alter table code.employ_types add constraint employ_types_code_key unique (code);
alter table code.employ_types add constraint pk_9cdwwv62b6hnp2ci6f3os4eoo primary key (id);
alter table code.enroll_modes add constraint enroll_modes_code_key unique (code);
alter table code.enroll_modes add constraint pk_obbn5syxqvad6epidl17icyh9 primary key (id);
alter table code.exam_forms add constraint exam_forms_code_key unique (code);
alter table code.exam_forms add constraint pk_4o5nmb6jnnouf32b3fc53ts8n primary key (id);
alter table code.exam_modes add constraint exam_modes_code_key unique (code);
alter table code.exam_modes add constraint pk_3d9q7b2ojv9amkt3csmo82ams primary key (id);
alter table code.exam_statuses add constraint exam_statuses_code_key unique (code);
alter table code.exam_statuses add constraint pk_m4l6snovqru1ghupjbjld8qft primary key (id);
alter table code.exam_types add constraint exam_types_code_key unique (code);
alter table code.exam_types add constraint pk_esav3g3q2ahu0i1l9d8g0k99y primary key (id);
alter table code.family_categories add constraint family_categories_code_key unique (code);
alter table code.family_categories add constraint pk_ji2x0f0kp1ggjq21mcx1f8c5d primary key (id);
alter table code.family_relationships add constraint family_relationships_code_key unique (code);
alter table code.family_relationships add constraint pk_7hi9tb37nkn1yeaj4nr5g01d primary key (id);
alter table code.fee_origins add constraint fee_origins_code_key unique (code);
alter table code.fee_origins add constraint pk_pjb9g9qkf41txh2q10u0knayp primary key (id);
alter table code.genders add constraint genders_code_key unique (code);
alter table code.genders add constraint pk_fbo2yxrjjfyqdyncfjyqmlhdb primary key (id);
alter table code.grade_types add constraint grade_types_code_key unique (code);
alter table code.grade_types add constraint pk_8fir0v1hr6yn19vre8j6h9ddj primary key (id);
alter table code.grading_modes add constraint grading_modes_code_key unique (code);
alter table code.grading_modes add constraint pk_otmdo5hmda4yu6iv5xxa07307 primary key (id);
alter table code.health_statuses add constraint health_statuses_code_key unique (code);
alter table code.health_statuses add constraint pk_ewtk7l63wlk6ptj855tfj5dfj primary key (id);
alter table code.household_types add constraint household_types_code_key unique (code);
alter table code.household_types add constraint pk_s7op8qppo9yfud198nlanf1pi primary key (id);
alter table code.hsk_levels add constraint hsk_levels_code_key unique (code);
alter table code.hsk_levels add constraint pk_ljbtoh8dew8tptj5qj2hvw4o primary key (id);
alter table code.id_types add constraint id_types_code_key unique (code);
alter table code.id_types add constraint pk_4yqih3x42nqjh4tigc0evwlgm primary key (id);
alter table code.institutions add constraint institutions_code_key unique (code);
alter table code.institutions add constraint pk_bfw2t7ynqlyotm6eyi4dwgtk9 primary key (id);
alter table code.job_statuses add constraint job_statuses_code_key unique (code);
alter table code.job_statuses add constraint pk_na0xycictcofkatnh5glv8day primary key (id);
alter table code.language_abilities add constraint language_abilities_code_key unique (code);
alter table code.language_abilities add constraint pk_qo5m05jp2cqjyioi5cll8fgar primary key (id);
alter table code.languages add constraint languages_code_key unique (code);
alter table code.languages add constraint pk_sdlywiif4qur2robjmciupw07 primary key (id);
alter table code.marital_statuses add constraint marital_statuses_code_key unique (code);
alter table code.marital_statuses add constraint pk_gq36i33myef28ldxfx4mjb2nl primary key (id);
alter table code.nations add constraint nations_code_key unique (code);
alter table code.nations add constraint pk_jae4hw2gt1sx4epxwbdkx3c12 primary key (id);
alter table code.passport_types add constraint passport_types_code_key unique (code);
alter table code.passport_types add constraint pk_gtg10x4u17ikg4x2fxlyxmgdy primary key (id);
alter table code.political_statuses add constraint pk_7xjjklfwlo69nyhtpoe3qx1sw primary key (id);
alter table code.political_statuses add constraint political_statuses_code_key unique (code);
alter table code.post_grades add constraint pk_lp7fwnrpynows9qmxo6uld7nb primary key (id);
alter table code.post_grades add constraint post_grades_code_key unique (code);
alter table code.post_types add constraint pk_4o6w1x4djydd1nskoh52mjr02 primary key (id);
alter table code.post_types add constraint post_types_code_key unique (code);
alter table code.press_grades add constraint pk_njmxmuicw8foumieqgjnko6cy primary key (id);
alter table code.press_grades add constraint press_grades_code_key unique (code);
alter table code.presses add constraint pk_rk7ek6u5edrwv9xxydg7bc48q primary key (id);
alter table code.presses add constraint presses_code_key unique (code);
alter table code.professional_grades add constraint pk_23d8s972h76b0xdatjfcxupe1 primary key (id);
alter table code.professional_grades add constraint professional_grades_code_key unique (code);
alter table code.professional_titles add constraint pk_cjq04j9bh6xleeky128k1gswt primary key (id);
alter table code.professional_titles add constraint professional_titles_code_key unique (code);
alter table code.publication_grades add constraint pk_r45qdwy0e7li10q5re3sfi8uf primary key (id);
alter table code.publication_grades add constraint publication_grades_code_key unique (code);
alter table code.publications add constraint pk_posqs7doguprjnunmq0nhxbvh primary key (id);
alter table code.publications add constraint publications_code_key unique (code);
alter table code.railway_stations add constraint pk_mwpmgne9kbs3rqkr9yimeky4b primary key (id);
alter table code.railway_stations add constraint railway_stations_code_key unique (code);
alter table code.religions add constraint pk_db95knst6ss1grofhc0kkrap4 primary key (id);
alter table code.religions add constraint religions_code_key unique (code);
alter table code.room_types add constraint pk_jru03m3vn58qmif6k5urq2y6s primary key (id);
alter table code.room_types add constraint room_types_code_key unique (code);
alter table code.social_unit_types add constraint pk_jt9a7ljhk01bsevoj0qbjw2y3 primary key (id);
alter table code.social_unit_types add constraint social_unit_types_code_key unique (code);
alter table code.staff_source_types add constraint pk_jsm380evxdo115plu90m5dmtc primary key (id);
alter table code.staff_source_types add constraint staff_source_types_code_key unique (code);
alter table code.staff_types add constraint pk_a4368uis6hkcnv1jksw7hntap primary key (id);
alter table code.staff_types add constraint staff_types_code_key unique (code);
alter table code.std_alter_reasons add constraint pk_33wxn4eyascc7730eqdyu8nap primary key (id);
alter table code.std_alter_reasons add constraint std_alter_reasons_code_key unique (code);
alter table code.std_alter_types add constraint pk_8eujmk9iw3oyow6csjap0m3jm primary key (id);
alter table code.std_alter_types add constraint std_alter_types_code_key unique (code);
alter table code.std_punishment_types add constraint pk_sefi5c7gqa45cyc6o4selwcb2 primary key (id);
alter table code.std_punishment_types add constraint std_punishment_types_code_key unique (code);
alter table code.student_statuses add constraint pk_r0abq98f6x7nppqxk49b1xc0 primary key (id);
alter table code.student_statuses add constraint student_statuses_code_key unique (code);
alter table code.study_types add constraint pk_m90ecgcdsvgkp9chbeuwwk9sk primary key (id);
alter table code.study_types add constraint study_types_code_key unique (code);
alter table code.teach_lang_types add constraint pk_r34pug3nqijvuda05m4ok825n primary key (id);
alter table code.teach_lang_types add constraint teach_lang_types_code_key unique (code);
alter table code.teaching_methods add constraint pk_s2ob7rrxiu3hwv3dgtwvik47a primary key (id);
alter table code.teaching_methods add constraint teaching_methods_code_key unique (code);
alter table code.teaching_natures add constraint pk_iidoc1hu3mfla79sh3ys7xr3c primary key (id);
alter table code.teaching_natures add constraint teaching_natures_code_key unique (code);
alter table code.tutor_types add constraint pk_blidh1mx6m4ci11jl2xhgmhyh primary key (id);
alter table code.tutor_types add constraint tutor_types_code_key unique (code);
alter table code.uee_subject_types add constraint pk_pp8tdd0qin0qphea92v03xq69 primary key (id);
alter table code.uee_subject_types add constraint uee_subject_types_code_key unique (code);
alter table code.uncheckin_reasons add constraint pk_b2456k7m08w83dfw2ofx5yvx primary key (id);
alter table code.uncheckin_reasons add constraint uncheckin_reasons_code_key unique (code);
alter table code.unregistered_reasons add constraint pk_a05jbnwecpcjh1vca74kq4u39 primary key (id);
alter table code.unregistered_reasons add constraint unregistered_reasons_code_key unique (code);
alter table code.user_categories add constraint pk_g22tbnb6clymkxmi560ll33em primary key (id);
alter table code.user_categories add constraint user_categories_code_key unique (code);
alter table code.visa_types add constraint pk_5u4p2t27gbgicni5lyayh6tlv primary key (id);
alter table code.visa_types add constraint visa_types_code_key unique (code);
alter table code.whereto_goes add constraint pk_4613lax8xj9thcny8sbdbs84j primary key (id);
alter table code.whereto_goes add constraint whereto_goes_code_key unique (code);
alter table code.work_statuses add constraint pk_ia5xweu6skbop6en26o5y4jxs primary key (id);
alter table code.work_statuses add constraint work_statuses_code_key unique (code);
alter table degree.advisors add constraint pk_i5l7e3g9bc2myekmmelts2qsv primary key (id);
alter table degree.advisors add constraint uk_jcnlieyxd426oafao9vvhfd17 unique (teacher_id);
alter table degree.advisors_departs add constraint pk_2gy4x53kvo6vxjqsof36u03gt primary key (advisor_id,department_id);
alter table degree.commitments add constraint pk_2wvfrxkxbdght6kk1hnen6o7f primary key (id);
alter table degree.commitments add constraint uk_9v8ek3ll64wdbb3m9ijcasn72 unique (writer_id);
alter table degree.copy_checks add constraint pk_ojj9g6o8ajtj1lbr9d01ede1w primary key (id);
alter table degree.deadlines add constraint pk_nh4p2cwv6qeb8mg4f3mx0d5ot primary key (id);
alter table degree.defense_groups add constraint pk_c45k166wf1ysch1e1xcftiwmm primary key (id);
alter table degree.defense_infoes add constraint pk_45baqcrd3wtuqspgq9nkaj4ya primary key (id);
alter table degree.defense_infoes add constraint uk_1s0h1diq6f0dwhhqwxe6pcykk unique (writer_id);
alter table degree.defense_members add constraint pk_p3aecabp96bs1ps09le2un6x3 primary key (id);
alter table degree.defense_notices add constraint pk_guoctyvgn106iuwq59325se1o primary key (id);
alter table degree.defense_writers add constraint pk_g6nqx0uyocsmdc3pgiropyt7n primary key (id);
alter table degree.defense_writers add constraint uk_1e633rm3u83fkxi1k13kky877 unique (writer_id);
alter table degree.depart_plans add constraint pk_fosmq37orxkj5i1049jfx7y7 primary key (id);
alter table degree.depart_plans_times add constraint pk_7ge72fgm68a7os42osuub2098 primary key (depart_plan_id,begin_on,stage,end_on);
alter table degree.guidances add constraint pk_ry9cqd94w60tjega5yn5hfcgc primary key (id);
alter table degree.guidances add constraint uk_o1tr5322a778ojj610im4awwf unique (writer_id);
alter table degree.midterm_check_details add constraint pk_nyl6q04c7r0mr6x6jsrcrw1ra primary key (id);
alter table degree.midterm_check_details add constraint uk_8n2cq37obd973bqb9gqmarwey unique (check_id,item_id);
alter table degree.midterm_check_items add constraint pk_o9eunp3w0qjk6ot39ivv7vi92 primary key (id);
alter table degree.midterm_checks add constraint pk_ltkl47flxa7xhbfixg14oo09j primary key (id);
alter table degree.midterm_checks add constraint uk_pgwmev6yuaj7l0gqamm8q318f unique (writer_id);
alter table degree.proposals add constraint pk_na7fgi69wfwklq4i2jw3k68n8 primary key (id);
alter table degree.proposals add constraint uk_ro29y4ytkhp4ejqadt59emj6w unique (writer_id);
alter table degree.subject_applies add constraint pk_cx4p6gchh5wjpf6v3yh2mq5pn primary key (id);
alter table degree.subject_applies add constraint uk_9wcnvhckvqrd0mclhi4y2cbjr unique (writer_id);
alter table degree.subjects add constraint pk_trw6rmspx195oy01rpbtghlsf primary key (id);
alter table degree.subjects add constraint uk_afynx14cx8h179uyu8gnwna1h unique (season_id,name);
alter table degree.subjects_majors add constraint pk_f9uumbw2vd9v3qwx1qd4edi4f primary key (subject_id,major_id);
alter table degree.thesis_checks add constraint pk_h3wix678400peq8mufhpn76u9 primary key (id);
alter table degree.thesis_checks add constraint uk_ogbi6lgf5f4fvxmghph3h9irs unique (season_id,writer_id);
alter table degree.thesis_docs add constraint pk_tjx4cxymbuw05ywcmv3mm73cr primary key (id);
alter table degree.thesis_docs add constraint uk_9yxnw8wag8f7k4aexkwmrjjnq unique (writer_id,stage);
alter table degree.thesis_papers add constraint pk_blkbqehyo53i9cn2bqleseray primary key (id);
alter table degree.thesis_papers add constraint uk_p14pjyoels7xfyutr26h795md unique (writer_id);
alter table degree.thesis_plans add constraint pk_tn31lepw015ftlf1hgvs8a8kj primary key (id);
alter table degree.thesis_plans_times add constraint pk_k4hptnvxacg3d67447oym5lrk primary key (thesis_plan_id,begin_on,stage,end_on);
alter table degree.thesis_reviews add constraint pk_pmutuonqxs4khwic666oq6yh primary key (id);
alter table degree.thesis_reviews add constraint uk_c5o3hq18aynpl1cvaqd0bsxbl unique (writer_id);
alter table degree.writers add constraint pk_m9q0hraod30jnt738610lw24f primary key (id);
alter table degree.writers add constraint uk_ii4fkei0dohqc92kvxlbbcopw unique (std_id,season_id);
alter table edu.c_certificate_categories add constraint c_certificate_categories_code_key unique (code);
alter table edu.c_certificate_categories add constraint pk_3m235cp2hv9v5i4utxpulo6bi primary key (id);
alter table edu.c_certificate_subjects add constraint c_certificate_subjects_code_key unique (code);
alter table edu.c_certificate_subjects add constraint pk_hs292w1wl5211w0714lgb7jw9 primary key (id);
alter table edu.c_clazz_tags add constraint c_clazz_tags_code_key unique (code);
alter table edu.c_clazz_tags add constraint pk_onkt7xkg420ekx0t7lbx5f2in primary key (id);
alter table edu.cert_exempt_applies add constraint pk_9mw6wwhdud4s410804223kes5 primary key (id);
alter table edu.cert_exempt_applies_courses add constraint pk_jin6irw0guks0awaktsymujxt primary key (cert_exempt_apply_id,course_id);
alter table edu.cert_signups add constraint pk_buvpy5j8eye2vtlladutvfisn primary key (id);
alter table edu.cert_signups add constraint uk_ox2hp3da9vvpwtuirtsrgtrdt unique (std_id,semester_id,subject_id);
alter table edu.certificate_grades add constraint pk_21bw15677thfojwd283r42rcx primary key (id);
alter table edu.certificate_grades add constraint uk_s5wek526ejranitx9q1nx2uxb unique (std_id,subject_id,acquired_on);
alter table edu.certificate_grades_exempts add constraint pk_nbymota90h5p6y4yvufp7nmea primary key (certificate_grade_id,course_id);
alter table edu.clazz_activities add constraint pk_5rankuhqjj88fbic1k8vl9ib0 primary key (id);
alter table edu.clazz_activities_rooms add constraint pk_mu2b4wc5pvt35yub2mwe0gndf primary key (activity_id,classroom_id);
alter table edu.clazz_activities_teachers add constraint pk_pikhy8td3magdbtgj9qqv6eqk primary key (activity_id,teacher_id);
alter table edu.clazz_book_stats add constraint pk_baqp1iuvt4utj5ya9hn3k8w9p primary key (id);
alter table edu.clazz_bulletins add constraint pk_qr18drp7kdfhmd4be5fgqvs2o primary key (id);
alter table edu.clazz_bulletins add constraint uk_bw61pgrg2iw0irmhs8hof0q0g unique (clazz_id);
alter table edu.clazz_groups add constraint pk_rk07cifqsq9cq5cscif6rre46 primary key (id);
alter table edu.clazz_materials add constraint pk_nrnf4gf44n88mvd5efhg9ror0 primary key (id);
alter table edu.clazz_notice_files add constraint pk_tc2n52103b3130x5jaaaxj7n1 primary key (id);
alter table edu.clazz_notices add constraint pk_dhgey9skl0nde8lg46v723xi2 primary key (id);
alter table edu.clazzes add constraint pk_3ra1a077so5k9mwdt2kxb3k0b primary key (id);
alter table edu.clazzes add constraint uk_8xuvd3v6lnrq5xmcl8jje0yau unique (project_id,semester_id,crn);
alter table edu.clazzes_ability_rates add constraint pk_kx0jp80tganm39yvlc4lewj74 primary key (clazz_id,course_ability_rate_id);
alter table edu.clazzes_tags add constraint pk_e1e2u69ixc5hje4f436327g1t primary key (clazz_id,clazz_tag_id);
alter table edu.clazzes_teachers add constraint pk_38x8fp2quo9ykkur4hvt7khir primary key (clazz_id,teacher_id,idx);
alter table edu.course_audit_results add constraint pk_e8y9knf7dh7k1rsjgal3b5d6x primary key (id);
alter table edu.course_audit_results add constraint uk_f9jth1bg1w3pq7io6y2wtmw7a unique (group_result_id,course_id);
alter table edu.course_grade_states add constraint pk_ss5mvl6jqttk0ubobqdhdni8u primary key (id);
alter table edu.course_grades add constraint pk_1ucmwigfmllurolusv5j8d5xv primary key (id);
alter table edu.course_grades add constraint uk_xitxltysiibv3efvpe69hk1j unique (std_id,course_id,semester_id,crn);
alter table edu.course_takers add constraint pk_r9e52tj7ca5ohhmokt4nw1h8e primary key (id);
alter table edu.course_takers add constraint uk_9pqkafkcyi7pe6799lg614vay unique (std_id,course_id,semester_id);
alter table edu.exam_activities add constraint pk_1n892fv0956m99fkw49r4k5y7 primary key (id);
alter table edu.exam_activities_rooms add constraint pk_6cw1w9e67eqd2bybivya2qb8h primary key (exam_activity_id,exam_room_id);
alter table edu.exam_grade_states add constraint pk_4wy4ksg5gx6h85tb11hphty4b primary key (id);
alter table edu.exam_grade_states add constraint uk_hbbjtria5w2yv76athjignsdk unique (grade_state_id,grade_type_id);
alter table edu.exam_grades add constraint pk_kgkg3a3map061ka3c7kevp21e primary key (id);
alter table edu.exam_grades add constraint uk_ij6eu0s9mftmblpso35iwm796 unique (course_grade_id,grade_type_id);
alter table edu.exam_groups add constraint pk_sibrdqqr0ie2m6sa4x21twlpa primary key (id);
alter table edu.exam_groups_rooms add constraint pk_ajbo1jbua6vqgkiifpob0wm72 primary key (exam_group_id,classroom_id);
alter table edu.exam_notices add constraint pk_k3c8i22sc17d5t4401t51p2ql primary key (id);
alter table edu.exam_room_groups add constraint pk_8e9jvyge9pm0yll17wkms3v01 primary key (id);
alter table edu.exam_room_groups_rooms add constraint pk_jxldkkl8o0nyifobrb87n1gj2 primary key (exam_room_group_id,classroom_id);
alter table edu.exam_rooms add constraint pk_ruuyfm4i7tf18lyint9kxx1i9 primary key (id);
alter table edu.exam_takers add constraint pk_3f19qyj4dhr0r0roi7ku4dbe1 primary key (id);
alter table edu.exam_takers add constraint uk_aw5c1boicjyshvgr1tbouf4r0 unique (std_id,clazz_id,exam_type_id);
alter table edu.exam_tasks add constraint pk_kpj9d25h0k6s95j7sov5ow3ee primary key (id);
alter table edu.exam_tasks add constraint uk_hblf5miprku52a8qklxm4lvpi unique (project_id,semester_id,code);
alter table edu.exam_tasks_rooms add constraint pk_2awcxprgxcvs7gi81idt6itnn primary key (exam_task_id,classroom_id);
alter table edu.exam_turns add constraint pk_7mybkgmuiw34nagg7ti6oui2b primary key (id);
alter table edu.exch_exempt_applies add constraint pk_dvqgwi75iysjg3gpvngqghb80 primary key (id);
alter table edu.exch_exempt_applies add constraint uk_tfut75r5ac76owasj8gt8642y unique (extern_student_id);
alter table edu.exch_exempt_credits add constraint pk_70ol4pjcehrrmb24hthnnu6no primary key (id);
alter table edu.execution_course_groups add constraint pk_i8ey4cvnf78oa7cq6536x3e7t primary key (id);
alter table edu.execution_plan_courses add constraint pk_8pnnwn3x0hml7i3beqlw29uwc primary key (id);
alter table edu.execution_plan_courses add constraint uk_jod7x8jyse63x23hd4uwhcaio unique (group_id,course_id);
alter table edu.execution_plans add constraint pk_5p24qpu2c2ydwpwg2qxabenb1 primary key (id);
alter table edu.exempt_courses add constraint pk_q2fwu5hjcpjwsvnda5gql38gq primary key (id);
alter table edu.exempt_courses_std_types add constraint pk_comjg7o4sak1o96o5jyca6spe primary key (exempt_course_id,std_type_id);
alter table edu.extern_grades add constraint pk_c6lgnfjsyt425c90aek6a4cba primary key (id);
alter table edu.extern_grades_exempts add constraint pk_1i3rqkxurk5pqwi4fjfxgqnul primary key (extern_grade_id,course_id);
alter table edu.final_exams add constraint final_exams_clazz_id_key unique (clazz_id);
alter table edu.final_exams add constraint pk_4whxkbjtpqflhys1ik6qa70y9 primary key (id);
alter table edu.final_makeup_courses add constraint pk_nb8vd6udx54xefb3ngrsm90f0 primary key (id);
alter table edu.final_makeup_courses_squads add constraint pk_ksgdtf4d0hu23dxxc2e6t0bl6 primary key (final_makeup_course_id,squad_id);
alter table edu.final_makeup_takers add constraint pk_eh01n7uwcd4vicj1mwrn7on3s primary key (id);
alter table edu.ga_grade_states add constraint pk_14dswddj9gfs9i2v6ep2m05ku primary key (id);
alter table edu.ga_grade_states add constraint uk_55c7tsme8v49y1o7tjn1r8vpe unique (grade_state_id,grade_type_id);
alter table edu.ga_grades add constraint pk_bvbnlqsyj55povhh0l0g94so2 primary key (id);
alter table edu.ga_grades add constraint uk_6l1n05tqq55sh661e6s1s12vm unique (course_grade_id,grade_type_id);
alter table edu.group_audit_results add constraint pk_mmbowc3nv9n1os7h68ubfddm6 primary key (id);
alter table edu.invigilation_clazz_quotas add constraint pk_21v272vaovqf9c0nuwoh1o095 primary key (id);
alter table edu.invigilation_clazz_quotas add constraint uk_99ht874j4b5ccw734m1h1moa0 unique (clazz_id,teacher_id);
alter table edu.invigilation_quota_details add constraint pk_6l5kr1v7rids4edf69va5n5lr primary key (id);
alter table edu.invigilation_quotas add constraint pk_91u61cmn1goxeqobsjde5pccq primary key (id);
alter table edu.invigilation_quotas add constraint uk_h35ysb0b74pj8foxdpfxvy0sv unique (invigilator_id,semester_id);
alter table edu.invigilation_quotas_excludes add constraint pk_i04mllgl8dh4whufiq0sw5smj primary key (invigilation_quota_id,exclude_on);
alter table edu.invigilations add constraint pk_bg0m2o403b43vb9mkg3noo1td primary key (id);
alter table edu.lessons add constraint pk_fha0ldq8mchqk0d5t5xy64chj primary key (id);
alter table edu.lessons_rooms add constraint pk_5wsidq7pwfg59ygpf47nl1qu6 primary key (lesson_id,classroom_id);
alter table edu.lessons_teachers add constraint pk_ole01ul2yg29w7shhjcf6rkh0 primary key (lesson_id,teacher_id);
alter table edu.major_alt_courses add constraint pk_scvgmvao9tsvfcm1whcnxvu3b primary key (id);
alter table edu.major_alt_courses_news add constraint pk_q055pvumg14plkk3p3dyb4v5o primary key (major_alternative_course_id,course_id);
alter table edu.major_alt_courses_olds add constraint pk_tfl42phv9abi60dnauh3cgtx5 primary key (major_alternative_course_id,course_id);
alter table edu.major_course_groups add constraint pk_3nxbhw8uol7n3nw0kpsdr6lvr primary key (id);
alter table edu.major_plan_courses add constraint pk_3wd4vyblbfks1j2lwty25qnbu primary key (id);
alter table edu.major_plan_courses add constraint uk_bmxrewotma5nd0dxovv1m77cw unique (group_id,course_id);
alter table edu.major_plans add constraint pk_ohol0jsnb6did1juitfw0awos primary key (id);
alter table edu.materials add constraint pk_590jmdlsq3houbgbs5xcy9f7f primary key (id);
alter table edu.materials add constraint uk_l4su5whmw7vaxq0fvig5238b6 unique (clazz_id);
alter table edu.materials_books add constraint pk_k8pcjsrbx6cdit80aycpv3rp4 primary key (material_id,textbook_id);
alter table edu.moral_grades add constraint pk_t3qyjinvsnfy0y84um9prvcmq primary key (id);
alter table edu.occupancies add constraint pk_cv4gsidr885aanuscffivwbb7 primary key (id);
alter table edu.plan_audit_results add constraint pk_mwb3u8lgw1wqcabq4x21w7jc1 primary key (id);
alter table edu.plan_audit_results add constraint uk_f6f86yl0ja9p2dveh9syviq2x unique (std_id);
alter table edu.program_doc_metas add constraint pk_rt39x9dho1u8xtaov9jms7p94 primary key (id);
alter table edu.program_doc_sections add constraint pk_7f7k9q32r86m55a0r93h2uflm primary key (id);
alter table edu.program_doc_templates add constraint pk_8e5naml4u9wbcyjrrhlmeb3ay primary key (id);
alter table edu.program_doc_templates_types add constraint pk_lwfg2w960gakch3fo4djc31d7 primary key (program_doc_template_id,std_type_id);
alter table edu.program_docs add constraint pk_tmprm3sm6os3l88qop5r89q9x primary key (id);
alter table edu.programs add constraint pk_9osl20jg9o3ywqs65190pgm9v primary key (id);
alter table edu.programs_degree_courses add constraint pk_c56n0ogp63uo4vcl3pp16l842 primary key (program_id,course_id);
alter table edu.programs_std_types add constraint pk_9ehq0f2rhqjce1anhhw5bcf4b primary key (program_id,std_type_id);
alter table edu.regular_grade_states add constraint pk_hnj9nkhhqpuj7yg9v7efhigo6 primary key (id);
alter table edu.regular_grade_states add constraint uk_nv0dulh1dhs6ddpd0clg8tvac unique (clazz_id);
alter table edu.regular_grade_states_percents add constraint pk_ljpyhuafbu8nwj7j6exu1wax1 primary key (regular_grade_state_id,value_,regular_test_type_id);
alter table edu.regular_grades add constraint pk_83v4fybspmj863btsicnyux6h primary key (id);
alter table edu.regular_grades add constraint uk_ek8kmmv077hq3rh4docowoqw7 unique (std_id,clazz_id);
alter table edu.regular_test_grades add constraint pk_5cprha5ugb0e1uuo3cuof6jxj primary key (id);
alter table edu.regular_test_grades add constraint uk_8n2yq76yji9pqu6q0ccfcymaw unique (regular_grade_id,test_type_id);
alter table edu.regular_test_types add constraint pk_t3a6autvcdxavg3jngtnoa9u7 primary key (id);
alter table edu.regular_test_types add constraint uk_pjg3i553nwubmj92t250lraw9 unique (name);
alter table edu.restriction_items add constraint pk_63rvwfjhs9fece5mm74976fc8 primary key (id);
alter table edu.restrictions add constraint pk_f453o9jrvoli7s141pd7lpl24 primary key (id);
alter table edu.room_applies add constraint pk_bc80rnoxs22g3i49cprrotgaq primary key (id);
alter table edu.room_applies_rooms add constraint pk_f3isa2ggycb2cyjdu9cg3ow5q primary key (room_apply_id,classroom_id);
alter table edu.room_applies_times add constraint pk_gut4id17joy6x8d5psmvc1pd2 primary key (room_apply_id,weekstate,begin_at,start_on,end_at);
alter table edu.room_available_times add constraint pk_72hrirupp9pfx9rkg0b30rct2 primary key (id);
alter table edu.room_occupy_apps add constraint pk_jhnnof3gdp1q99769e6htdi2x primary key (id);
alter table edu.schedule_suggest_activities add constraint pk_myer3gf4y362usk4aho5ppl6t primary key (id);
alter table edu.schedule_suggests add constraint pk_huj196fcrgxy8bfyiavvr2qxg primary key (id);
alter table edu.schedule_suggests add constraint uk_p580lu918uyus7rr6weynmg2i unique (clazz_id);
alter table edu.share_course_groups add constraint pk_45hb6362voxm23n8sxy3fgo3b primary key (id);
alter table edu.share_plan_courses add constraint pk_d5aukjiewdmk6smt3dwg7s8cq primary key (id);
alter table edu.share_plan_courses add constraint uk_4g3u5b9itdu90iij2y6la2ms5 unique (group_id,course_id);
alter table edu.share_plans add constraint pk_i76on9h6wjqohanirds5n3flp primary key (id);
alter table edu.std_alt_courses add constraint pk_fwqlciau51sypm3cjvy7rsqgp primary key (id);
alter table edu.std_alt_courses_news add constraint pk_ff9ka4gw208d53tn5bmg8v3yo primary key (std_alternative_course_id,course_id);
alter table edu.std_alt_courses_olds add constraint pk_9lvrx45u53eynsj63a4c345rl primary key (std_alternative_course_id,course_id);
alter table edu.std_book_orders add constraint pk_8233g912nk0k7gyf7ubaa3yf6 primary key (id);
alter table edu.std_course_abilities add constraint pk_ctriq5lvqq54p8st9q7qkkg20 primary key (id);
alter table edu.std_course_groups add constraint pk_br4kq5lj281tok3i7bqla6v3r primary key (id);
alter table edu.std_credit_stats add constraint pk_ifimhatpwc1ygx0mmukl2qkjn primary key (id);
alter table edu.std_gpas add constraint pk_d8hmmf1mnbxhuj1fi91q1n9rj primary key (id);
alter table edu.std_gpas add constraint uk_1pgtli4u8gcx191biigqq6mty unique (std_id);
alter table edu.std_plan_courses add constraint pk_sw97n0tnorl3stkr4q9s5vo8n primary key (id);
alter table edu.std_plan_courses add constraint uk_9ume0khx1eqjh5l7v7lsp3gjf unique (group_id,course_id);
alter table edu.std_plans add constraint pk_n7x5kawng3p8xqf5wfya9s6ns primary key (id);
alter table edu.std_plans add constraint uk_jo5xh73ptavgr1lk7p0sfpamw unique (std_id);
alter table edu.std_semester_gpas add constraint pk_fqb6mob02oox7m3qiy43y5g3f primary key (id);
alter table edu.std_semester_gpas add constraint uk_54djya8v8f1shu5uutr9e555e unique (std_gpa_id,semester_id);
alter table edu.std_year_gpas add constraint pk_3ad0t5p7c2vmp6ktrbtgiwbwb primary key (id);
alter table edu.std_year_gpas add constraint uk_e0src4xf9uskqtilum6e01344 unique (std_gpa_id,school_year);
alter table edu.subclazzes add constraint pk_r86ec4dvfg6l28xam7g5sunpt primary key (id);
alter table edu.syllabus_files add constraint pk_45v91qs7o9qg0dvr6dxtp27yc primary key (id);
alter table edu.syllabuses add constraint pk_djhmwl2mslpebwr381gmwjina primary key (id);
alter table edu.teaching_loads add constraint pk_s4s5ejob4j5b5skxdivgcndvk primary key (id);
alter table edu.teaching_plans add constraint pk_fr5ve3vinn52vwsit7lgqxsjv primary key (id);
alter table edu.term_campuses add constraint pk_e8xtqcnfg6h5q2vv9bicgyyo1 primary key (id);
alter table log.edu_room_apply_audit_logs add constraint pk_ocfq5rdpfs7hbgaukwe3r0a3x primary key (id);
alter table log.spa_download_logs add constraint pk_lcqw7ty5jppf59n7h1l8uhbwq primary key (id);
alter table log.spa_print_logs add constraint pk_2nfredgb8p5h5rejmbm3nwr5m primary key (id);
alter table log.std_transfer_apply_logs add constraint pk_je8lknq8ke5qe3u8vjyxrbqlo primary key (id);
alter table prac.inv_batches add constraint pk_26eu4n6mvkkawtd9p8nyc58wb primary key (id);
alter table prac.inv_closure_review_details add constraint pk_1b4ggxr300ebb51fc212hx4r primary key (id);
alter table prac.inv_closure_review_groups add constraint pk_6c4rjcbht2592mtspwayi9kar primary key (id);
alter table prac.inv_closure_review_groups_experts add constraint pk_8ul02gtuobjohhs8hbfqh5b2i primary key (closure_review_group_id,expert_id);
alter table prac.inv_closure_reviews add constraint pk_c86a40ptsd4av8ra1ctcutent primary key (id);
alter table prac.inv_closures add constraint pk_22ch6g6tq6697mf0d2l4ip6vn primary key (id);
alter table prac.inv_experts add constraint pk_2g4o8wotk79thelc7ggmeyfgf primary key (id);
alter table prac.inv_init_review_details add constraint pk_djyah74eyn02aqlimc34rongv primary key (id);
alter table prac.inv_init_review_groups add constraint pk_kwq4d0u1l01n5ckhm2acefd1l primary key (id);
alter table prac.inv_init_review_groups_experts add constraint pk_i3cm734r0fyam45ukbs5kdscb primary key (init_review_group_id,expert_id);
alter table prac.inv_init_reviews add constraint pk_k50vknsvhw3h9xacr5qryrub7 primary key (id);
alter table prac.inv_introes add constraint pk_7uyfsg7aoqw6b5em74nj1ycqe primary key (id);
alter table prac.inv_level_jounals add constraint pk_p32r7mb8i2943uveupn0n815a primary key (id);
alter table prac.inv_materials add constraint pk_3ouunikiphs7y50md8yv0at1y primary key (id);
alter table prac.inv_members add constraint pk_de3fosi9vb65pxv8s5f849fxs primary key (id);
alter table prac.inv_members add constraint uk_nqejhpjmj9jdt59pxnaxsyf8a unique (project_id,std_id);
alter table prac.inv_project_categories add constraint pk_mx8lpbqvtwtv3npu3t3dntbl4 primary key (id);
alter table prac.inv_project_levels add constraint pk_742eum08363tyw0rae780jcuo primary key (id);
alter table prac.inv_project_states add constraint pk_a9a7lsr3hvbjd33wxdtwakhjy primary key (id);
alter table prac.inv_projects add constraint pk_6rijukmxxnvtd3a5b1xbc92rm primary key (id);
alter table prac.inv_projects_instructors add constraint pk_jsow4fy8ru7u15bh43on17jx2 primary key (project_id,teacher_id,idx);
alter table prac.inv_stage_types add constraint pk_rxwn79ifobeyupjueaxnwqksi primary key (id);
alter table prac.inv_stages add constraint pk_mnxxfplf9544qamdh72e4gody primary key (id);
alter table qos.assess_criterias add constraint pk_mbg8mfxchlyxb3rbpr5wophpe primary key (id);
alter table qos.assess_grades add constraint pk_cwbj8vblm76ow6w1i093jmtli primary key (id);
alter table qos.category_eval_stats add constraint pk_bq3ia61jmui8sv480n1sxf9ao primary key (id);
alter table qos.category_stat_grades add constraint pk_pmn7bnvtdgb2b8csk8dhtwtsi primary key (id);
alter table qos.category_stat_ranges add constraint pk_cv2ip2dgyo0tdy2p0ung5jpi5 primary key (id);
alter table qos.course_eval_stats add constraint pk_29v0q7x5wi3rvbtua754ljbo primary key (id);
alter table qos.course_indicator_stats add constraint pk_7jjkpgkgirlgdymq0juu64gy7 primary key (id);
alter table qos.course_option_stats add constraint pk_otrkkbyi100meit14vwi9ecqt primary key (id);
alter table qos.course_question_stats add constraint pk_rmgevn8gy92r0w10mmk5s7xyj primary key (id);
alter table qos.depart_eval_stats add constraint pk_p87qmm6ecwo7f9x37labrlk4y primary key (id);
alter table qos.evaluate_results add constraint pk_sjln57t9wh1oadhcwy8aiagck primary key (id);
alter table qos.feedbacks add constraint pk_3w69do02finwr5csfag3hr00u primary key (id);
alter table qos.final_comments add constraint pk_hh645iewh252rbq6jbpvlpuj1 primary key (id);
alter table qos.final_teacher_scores add constraint pk_9cv4kydmlobvgybnqpyyw68a primary key (id);
alter table qos.indicators add constraint pk_sfq7ixip97pxv9a4ug1sgwd3k primary key (id);
alter table qos.option_groups add constraint pk_gvmhlgmsyrwjo92qnevi2x234 primary key (id);
alter table qos.options add constraint pk_h7d0xw570w8ojgjkwivq1cng6 primary key (id);
alter table qos.question_results add constraint pk_rcpahtmwk6gyixcqpqcvwdtku primary key (id);
alter table qos.questionnaire_clazzes add constraint pk_arlumvuig3w4s661mswyvlteg primary key (id);
alter table qos.questionnaires add constraint pk_fufcai5j6hvvlr0wc6fpb8d6o primary key (id);
alter table qos.questionnaires_questions add constraint pk_41ugco3nqnt9c9x9taga06agn primary key (questionnaire_id,question_id);
alter table qos.questions add constraint pk_8be2ix7e7pkg5mjne8qegaj76 primary key (id);
alter table qos.school_eval_stats add constraint pk_qtq0xmlybs0ch9pjdq4cbpom2 primary key (id);
alter table spa.print_quotas add constraint pk_st8emevheay237gju9wkv7y2p primary key (id);
alter table std.bills add constraint pk_l2ycbilgr05krq0lg8r6qxnsp primary key (id);
alter table std.contacts add constraint pk_7ko2w4r57qng8yfiyi7n9snh4 primary key (id);
alter table std.contacts add constraint uk_qopxi21m45bqtuemmwurk7dkl unique (std_id);
alter table std.debts add constraint pk_hv6munekg3kbg6qh7yodxld9l primary key (id);
alter table std.degree_applies add constraint pk_85xktk94x3o87fc7wwtbo07i5 primary key (id);
alter table std.degree_audit_items add constraint pk_p1g6j1m2uwxsqw5s7uypyirnh primary key (id);
alter table std.degree_results add constraint pk_juk8stxairvjh8aqqgmus1vx2 primary key (id);
alter table std.edu_work_records add constraint pk_ow2kjrrf2ckemfeaucvejvy7u primary key (id);
alter table std.examinees add constraint pk_1e8il6rh29256vdjtbwh1y0fe primary key (id);
alter table std.examinees add constraint uk_2bqu9xw63m537f7cby311u7vr unique (std_id);
alter table std.exchange_programs add constraint pk_md99sroe2nv8btxk3cr7tp2an primary key (id);
alter table std.exchange_programs_schools add constraint pk_da8usceea51yrhkys93r6wcgw primary key (exchange_program_id,extern_school_id);
alter table std.foreigners add constraint pk_tr2lwiprket01b5xwsnoci4qd primary key (id);
alter table std.freshmen add constraint pk_lyewxqqmbjf9rgu4w4se50ddk primary key (id);
alter table std.graduate_audit_items add constraint pk_dhwdi0ipn8oajjhrfb16u0ud primary key (id);
alter table std.graduate_batches add constraint pk_kb2t7xdi7imcxukogahdjojtq primary key (id);
alter table std.graduate_results add constraint pk_pwaqdnrn36ry8ef21e1k1kmu5 primary key (id);
alter table std.homes add constraint pk_ry45w9bb9c30yransxedxfoop primary key (id);
alter table std.homes add constraint uk_t42cafsv2e1s4k9l1rxdixf2x unique (std_id);
alter table std.honor_awards add constraint pk_82a0vokwcnncj8l0yi0s57wvc primary key (id);
alter table std.honor_categories add constraint pk_a6ucjxdfau1g7x22o5n014q2u primary key (id);
alter table std.honor_levels add constraint pk_l53d6eu3akfl5s2gq3o74wqa9 primary key (id);
alter table std.honor_types add constraint pk_c1tngwju5h6efg1jlicg9tvtj primary key (id);
alter table std.major_students add constraint pk_ge7r9q9q5db7ne2cfjul9pnm5 primary key (id);
alter table std.major_students add constraint uk_sp5y2w7s2e9uwp4okyf64ag63 unique (std_id);
alter table std.orders add constraint orders_code_key unique (code);
alter table std.orders add constraint pk_26gf4ikas867gkkiyjur6i708 primary key (id);
alter table std.orders add constraint uk_5rbs2yuu4l5occesk8783g2sh unique (bill_id);
alter table std.punishments add constraint pk_n9h4mdiiwcc2512hqfwdu3w3 primary key (id);
alter table std.registers add constraint pk_6x7adbm1t7y079qhsobs4n9il primary key (id);
alter table std.scholarship_awards add constraint pk_56u7g5vxife5b22kc1duq23ua primary key (id);
alter table std.scholarship_categories add constraint pk_mq52nlda4709qvl5frjenasyv primary key (id);
alter table std.scholarship_levels add constraint pk_e1wrr4oa17lgng47f5rp1r862 primary key (id);
alter table std.scholarship_types add constraint pk_61wg2qxbi9mvbo8u75rkflwrx primary key (id);
alter table std.social_relations add constraint pk_kqm1n06eaj1ydahbybcgtgqn2 primary key (id);
alter table std.std_alteration_items add constraint pk_o3d8j0mujuxorms8a36jw7ic5 primary key (id);
alter table std.std_alterations add constraint pk_a1ti0uv32d4ggaivn3y58e9c primary key (id);
alter table std.stipend_awards add constraint pk_7j9vvyns0himgc9ubwkixdnqa primary key (id);
alter table std.stipend_categories add constraint pk_fcn9q6gllh4ox76aycyatqgy8 primary key (id);
alter table std.stipend_levels add constraint pk_s2ptwfu0qp30q386yx6iedxsl primary key (id);
alter table std.subsidy_awards add constraint pk_2i78s7uvy951i87lqysmnm8a3 primary key (id);
alter table std.subsidy_categories add constraint pk_rrvx3ixuv9tqwxova51722juy primary key (id);
alter table std.subsidy_levels add constraint pk_h223qwt0qq24unbms55y0q5bp primary key (id);
alter table std.transfer_applies add constraint pk_1636v9ke8tssygsebwc8he7ex primary key (id);
alter table trd.c_rd_achievement_types add constraint c_rd_achievement_types_code_key unique (code);
alter table trd.c_rd_achievement_types add constraint pk_s4hrxsthg6t50hx822ex2hm9s primary key (id);
alter table trd.c_rd_award_grades add constraint c_rd_award_grades_code_key unique (code);
alter table trd.c_rd_award_grades add constraint pk_ioa5fk53393f40cjpfs5k3c77 primary key (id);
alter table trd.c_rd_levels add constraint c_rd_levels_code_key unique (code);
alter table trd.c_rd_levels add constraint pk_og5hhd27lnh0mkncdtyx6p8ol primary key (id);
alter table trd.c_rd_project_categories add constraint c_rd_project_categories_code_key unique (code);
alter table trd.c_rd_project_categories add constraint pk_7iu8cm1s0ud6qt6tufrgiqavv primary key (id);
alter table trd.c_rd_project_statuses add constraint c_rd_project_statuses_code_key unique (code);
alter table trd.c_rd_project_statuses add constraint pk_9dvpgojx972wqvhka58069g0x primary key (id);
alter table trd.rd_achievement_awards add constraint pk_jrurc91k5s98dupbvbiucs605 primary key (id);
alter table trd.rd_achievement_members add constraint pk_13aseiekqtn3gmtqw4u0ortdo primary key (id);
alter table trd.rd_achievements add constraint pk_kcqw8m7fdba9xh17q6sm4kxtd primary key (id);
alter table trd.rd_project_members add constraint pk_fx6ud9yt7chj5wgi8jsjxe1vd primary key (id);
alter table trd.rd_projects add constraint pk_sn8pn1wp0f8awmjy42hcmnmoc primary key (id);
alter table trd.rd_projects_leaders add constraint pk_te6ajmxgr9o0402uvfenplpvh primary key (rd_project_id,user_id);
alter table trd.teaching_team_members add constraint pk_b0hsatym04m5isj6oxjjmmfbb primary key (id);
alter table trd.teaching_teams add constraint pk_k1qfb3g4prtlvhoqsw3cq0ska primary key (id);
alter table trd.teaching_teams_leaders add constraint pk_aqg74musb0j1qtonp6uy9vupg primary key (teaching_team_id,user_id);
alter table trd.textbook_achievements add constraint pk_301jawapmi8866dn1wo04dr62 primary key (id);
alter table trd.textbook_awards add constraint pk_mf7o4jj1qfw8k0d3akw2g95s7 primary key (id);
alter table trd.textbook_editors add constraint pk_6l1cf8pefv3kvorgvxyk7qrm8 primary key (id);
