caffeine.jcache {
  default {
    policy {
      maximum {
        size = 50000
      }
      lazy-expiration {
        creation = 5m
        update = 5m
        access = 5m
      }
    }
  }

  openurp {
    policy {
      maximum {
        size = 50000
      }
      lazy-expiration {
        creation = 5m
        update = 5m
        access = 5m
      }
    }
  }

  default-update-timestamps-region{
    policy{
      maximum{
        size = 10000
      }
      lazy-expiration {
        creation = 5m
        update = 5m
        access = 5m
      }
    }
  }

  default-query-results-region{
    policy{
      maximum{
        size = 10000
      }
      lazy-expiration {
        creation = 5m
        update = 5m
        access = 5m
      }
    }
  }
}

logging {
  level {
    org.hibernate.orm.connections.pooling = ERROR
  }
}
